### ISSUE TITLE
cross building for windows

### ISSUE THREAD

**Issue by PerlTester** [wkhtmltopdf/packaging#10]
Hi ashkulz,

I'm running builds using the new packaging model with vagrant and virtual box on ubuntu 18.04 LTS (a vm on my esxi5.5 host) and successfully have built wkhtmltopdf for linux, but am having a gruelling time trying to get a windows build going.

I have a standard newly built ubuntu 18.04 and installed the necessaries with 

sudo apt install -y python-yaml docker.io vagrant virtualbox p7zip-full, 

then onward upgrading to the latest vagrant and virtual box however I am getting the now famous net::ssh errors that are all over the web etc, I have tried everything, even trying to build on 16.04 with different versions of vagrant and virtualbox using other mcandre boxes etc. but to no avail.

commandline output below...

test@srv_ub64_009:~/packaging$ sudo ./build vagrant msvc2015-win64 /home/test/wkhtmltopdf/
Bringing machine 'windows' up with 'virtualbox' provider...
==> windows: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> windows: flag to force provisioning. Provisioners marked to run always will still run.
ssh_exchange_identification: read: Connection reset by peer
ssh -F vagrant/.vagrant/windows_config windows -- mkdir -p /c/Users/vagrant/msvc2015-win64
command failed: exit code 255

Did you manage a windows build successfully with this new model and if so can you share the vagrant versions etc.

Many thanks

Perl Tester.

**Comment by ashkulz** [comment]
Why are you running under sudo? Also, try ./build vagrant --clean as it looks like the VM didn't get provisioned correctly. Post the complete log of a clean build, as all releases use these scripts.

**Comment by ashkulz** [comment]
If you want, you can also run it directly on Windows ... see the appveyor configuration on how to do that.

**Comment by PerlTester** [comment]
Thanks I'll have look

**Comment by PerlTester** [comment]
OK after moving to desktop ubuntu and setting the gui flag I have found that the issue is related to virtualisation VT not enabled in the client VM bios, running in esxi5.5. - basically nested virtual machines need to be supported.

To enable this in esxi5.5 is described here:
https://www.codementor.io/slavko/enable-virtualization-inside-esxi-virtual-machine-du107l4ky

Thanks again

P.

**Comment by ashkulz** [comment]
Please reopen if you face any issue in the compilation process. Feel free to submit a PR mentioning the requirement for physical hardware or nested VT.
