### ISSUE TITLE
Get binaries with unpatched qt

### ISSUE THREAD

**Issue by velcrine** [wkhtmltopdf/packaging#102]
I see that results of pdf with wkhtmltopdf(unpatched qt) are way better than with patched qt. 
Please tell, where can I get those builds as ubuntu by default gives unpatched qt, but I also require downloadable packages.

**Comment by ashkulz** [comment]
Just do `apt-get install wkhtmltopdf`? The official distro packages **are** the unpatched Qt binaries.

**Comment by velcrine** [comment]
they don't give ability to import # include wkhtmltox/pdf.h

I need to utilize the bindings too, and give my customer the best pdf experience...

**Comment by velcrine** [comment]
please reopen

**Comment by ashkulz** [comment]
You can just do `apt build-dep wkhtmltopdf` and then just do `qmake && make` in the source checkout -- all the binaries will be in `bin/`.

**Comment by velcrine** [comment]
oh thanks ashkulz
let me try that.

**Comment by ashkulz** [comment]
Nope, the submodule doesn't get used -- it uses the system Qt dependencies (`apt build-dep` is for that).

**Comment by velcrine** [comment]
oh thanks!!
