### ISSUE TITLE
Binary build for web serveur

### ISSUE THREAD

**Issue by Ph0tonic** [wkhtmltopdf/packaging#107]
Hello,

I'm currently trying to build a binary for the following config:
- Linux version 4.18.0-305.19.1.lve.el8.x86_64 (mockbuild@koji.corp.cloudlinux.com) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Thu Sep 23 11:04:54 EDT 2021

However, I have no sudo rights so I'm not able to use dpkg or any package manager on the server.

The previous generic build 0.12.4 is not working due to SSL issues.
- https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

Any help would be welcome.

Thanks,

**Comment by ashkulz** [comment]
Please read https://wkhtmltopdf.org/downloads.html#why-are-there-no-generic-linux-builds-which-were-provided-earlier

You can try extracting from the CentOS 8 rpm, but it may fail due to dependent libraries being missing.

**Comment by Ph0tonic** [comment]
Thanks, it worked perfectly 👍
