### ISSUE TITLE
SSH command syntax incorrect

### ISSUE THREAD

**Issue by PerlTester** [wkhtmltopdf/packaging#11]
Hi,
Doing a windows build using the new packaging module I get past invoking the virtualbox mcandre/windows-amd64 and successfully ssh into the vm to begin building the pre requisites for a windows build but get stuck on ...

The syntax of the command is incorrect.
ssh -F vagrant/.vagrant/windows_config windows -- mkdir -p /c/Users/vagrant/msvc2015-win64
command failed: exit code 1

![image](https://user-images.githubusercontent.com/2702901/43967248-44a4e91e-9cc4-11e8-9a7b-fb4e35ebbbc5.png)

Building on Ubuntu 18.04 server with standard packaging git cloned

**Comment by PerlTester** [comment]
Looks like the -p directive for mkdir is not supported in Windows and the target directory should have the widows format, as in \c:\Users\vagrant\msvc2015-win64

**Comment by ashkulz** [comment]
Weird, the vagrant image should start under git-bash. Are you on a physical Ubuntu machine?

**Comment by PerlTester** [comment]
no I have ubuntu 18.04 as a virtual machine running in esxi5.5 and it
spawns a virtual box mcandre/windows-amd64 to ssh into as per the build
python in the packaging modeland thats where I am stuck now.

Thanks

P.

**Comment by franjaviersans** [comment]
Hello @PerlTester , did you manage to solve the issue? I'm also stuck in the same place.

**Comment by PerlTester** [comment]
Hi Francisco,

Sorry fro not replying sooner but no I did not get it solved in an
automated way unfortunately. I ended up hacking the beast and manually
copying the source code across to the windows VM and then running the build
process manually.
Maybe you can provide some details to Ashish and see if he can help given
that the problem has affected someone else.

On the question of the build of wkhtml what is your use case? for me it was
to get landscape orientation on individual pages other than globally, but I
have an issue on certain pages where I have table bleed it is pushing my
TOC page numbering out by 2 each time - not sure if you are in that space
but maybe you have an idea?

Thanks

P.

**Comment by ashkulz** [comment]
I recently rebuilt my machine, and I'm now getting this error as well. Should be having a fix for it in a day or two.

**Comment by PerlTester** [comment]
Thanks Ashish,

P.

**Comment by ashkulz** [comment]
@PerlTester, @franjaviersans: can you try with the latest commit and let me know if it doesn't work?

**Comment by franjaviersans** [comment]
Hello @ashkulz . I tried to build the msvc2015-win64 target and I couldn't do it.

I receive this:

==> windows: Waiting for machine to boot. This may take a few minutes...
    windows: SSH address: 127.0.0.1:2200
    windows: SSH username: vagrant
    windows: SSH auth method: private key
Timed out while waiting for the machine to boot.

But again, I am running the program on a Ubuntu inside a VMware Workstation.

**Comment by ashkulz** [comment]
Any particular reason why you're doing it via nested VMs? You might try to increase the boot timeout if you continue with that approach, it's bound to be very slow otherwise.

Also, if you see the [Travis CI configuration](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/af3694d8/.travis.yml#L52), you can easily bootstrap it on a Windows VM ... the only reason I set it up this way is because I use Linux as my main OS :smile:

**Comment by franjaviersans** [comment]
Yeah, the thing is that I use Windows as main OS and I don't have any Ubuntu system at my disposal.

**Comment by ashkulz** [comment]
Then just run the commands linked above and see if you can get a build working directly on Windows (assumes you have chocolatey installed).
