### ISSUE TITLE
execute  ./build package-docker buster-amd64 <PATH-TO-WKHTMLTOPDF> appear a error

### ISSUE THREAD

**Issue by lishuaiyin02** [wkhtmltopdf/packaging#111]
In ubuntu 20.04 when I  execute  sudo apt install -y python-yaml docker.io vagrant virtualbox p7zip-full. And then execute  ./build package-docker buster-amd64 <PATH-TO-WKHTMLTOPDF>, appear a error : You don't seem to have 'make' or 'gmake' in your PATH.Cannot proceed,what should I do to solve this problem.
![image](https://user-images.githubusercontent.com/43161391/159447341-d4a8d14c-7b34-4398-a554-bb0f064154da.png)
Because I am a newbie and my English is poor, so there may be errors in the expression. Please forgive me. Thanks!

**Comment by ashkulz** [comment]
@lishuaiyin02 I'm not sure which version of the `packaging` repo you're using, but it should attempt to create a docker image. Can you check with the latest `master`?
