### ISSUE TITLE
Building NPM package with wkhtmltopdf as dependency

### ISSUE THREAD

**Issue by DHVPP** [wkhtmltopdf/packaging#112]
Hello, 

I'm building a native module for Nodejs using wkhtmltox package. Right now, in our bindings configuration we are using the libwkhtmltox.so file to compile our package and it works perfectly, on my PC. 

As far as I understood, I need a static version of this file to be compiled with my package, but I'm having trouble finding a way to recompile wkhtmltox package to include this file.

Could you please point me to the right direction as to where to look and if this thinking of mine is right, as this is the fist time I'm working with native packages.

Thanks for the read.

**Comment by ashkulz** [comment]
This won't work, as you'll need a version for every supported distro and then depending on the relevant distro use that binary. See [wkhtmltopdf_binary_gem](https://github.com/zakird/wkhtmltopdf_binary_gem) on how a similar approach in Ruby works.

**Comment by DHVPP** [comment]
Thank you so much for the replay.

I made this package primarily for my clients project  which runs only on Ubuntu 18.04. So if this approach could would work only for one distro right now, I'd be grateful if you could tell me how to build the static version of this file.

Thanks again

**Comment by ashkulz** [comment]
Download [this package](https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb) (_assuming you're using amd64_) and google from `extract from deb` -- you should be able to extract the `libwkhtmltox.so.0.12.6` from it (_you can rename it to `libwkhtmltox.so` if you want_).

**Comment by DHVPP** [comment]
I'm sorry to be reopening this issue, but I might have not explained myself as well as I should have. This client project is an Electron application that uses my package for printing (wkhtmltox is used for fast conversion of html to pdf before printing), so using shared object is not ideal as it would require maintenance on 3000 PCs before the update of the application is run. All i need is info on how to create a static object for Ubuntu 18.04 OS as that's the only OS that is running the App right now, so that the app could be compiled with that .a object. 

Thanks again for your time.

**Comment by DHVPP** [comment]
We haven't decided yet on the license we are going to use, but if complying with LGPLv3 is required for us to successfully ship this package with static linking to wkhtmltox, we would gladly comply.
