### ISSUE TITLE
Debian Bullseye package support

### ISSUE THREAD

**Issue by SpootyMcSpoot** [wkhtmltopdf/packaging#116]
Currently for debian I am only seeing packages available up to bionic release. I would like to request support for bullseye so as to keep on the edge of security fixes from upstream images.

New debian release: https://www.debian.org/releases/bullseye/

Currently listed packages: https://github.com/wkhtmltopdf/packaging/releases/0.12.6-1

**Comment by ashkulz** [comment]
The current `buster` release should work on bullseye. I need to wrap up #101 but I need to finish the migration to GitHub Actions.

**Comment by ashkulz** [comment]
Builds have been published to the website: see wkhtmltopdf/wkhtmltopdf@e59bfcce3e8db83341264bdd75d996319402ccff. The Raspberry Pi build failed and is being retried.
