### ISSUE TITLE
command failed: exit code 1

### ISSUE THREAD

**Issue by ABetterCat** [wkhtmltopdf/packaging#117]
When i run `./build package-docker centos7-x86_64 /root/wkhtmltopdf-master`
It exit.

`sudo ./build package-docker centos7-x86_64 /root/wkhtmltopdf-master

latest: Pulling from aptman/qus
462eb288b104: Pulling fs layer
462eb288b104: Pull complete
d8ed95a72fb1: Pull complete
175e19796fa9: Pull complete
0b3dd78fa988: Pull complete
e8cb327247ec: Pull complete
Digest: sha256:5ecc37ce5e2c6cf727797b30443e40b2bc8d1511b04f6f452992ec95baccd653
Status: Downloaded newer image for aptman/qus:latest
docker.io/aptman/qus:latest
cat ./qemu-binfmt-conf.sh | sh -s -- --path=/qus/bin -r
cat ./qemu-binfmt-conf.sh | sh -s -- --path=/qus/bin -p --suffix -static
sh: write error: Invalid argument
Setting /qus/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /qus/bin/qemu-arm-static as binfmt interpreter for arm
sh: write error: Invalid argument
Setting /qus/bin/qemu-armeb-static as binfmt interpreter for armeb
sh: write error: Invalid argument
Setting /qus/bin/qemu-sparc-static as binfmt interpreter for sparc
sh: write error: Invalid argument
Setting /qus/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
sh: write error: Invalid argument
Setting /qus/bin/qemu-sparc64-static as binfmt interpreter for sparc64
sh: write error: Invalid argument
Setting /qus/bin/qemu-ppc-static as binfmt interpreter for ppc
sh: write error: Invalid argument
Setting /qus/bin/qemu-ppc64-static as binfmt interpreter for ppc64
sh: write error: Invalid argument
Setting /qus/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
sh: write error: Invalid argument
Setting /qus/bin/qemu-m68k-static as binfmt interpreter for m68k
sh: write error: Invalid argument
Setting /qus/bin/qemu-mips-static as binfmt interpreter for mips
sh: write error: Invalid argument
Setting /qus/bin/qemu-mipsel-static as binfmt interpreter for mipsel
sh: write error: Invalid argument
Setting /qus/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
sh: write error: Invalid argument
Setting /qus/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
sh: write error: Invalid argument
Setting /qus/bin/qemu-mips64-static as binfmt interpreter for mips64
sh: write error: Invalid argument
Setting /qus/bin/qemu-mips64el-static as binfmt interpreter for mips64el
sh: write error: Invalid argument
Setting /qus/bin/qemu-sh4-static as binfmt interpreter for sh4
sh: write error: Invalid argument
Setting /qus/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
sh: write error: Invalid argument
Setting /qus/bin/qemu-s390x-static as binfmt interpreter for s390x
sh: write error: Invalid argument
Setting /qus/bin/qemu-aarch64-static as binfmt interpreter for aarch64
sh: write error: Invalid argument
Setting /qus/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
sh: write error: Invalid argument
Setting /qus/bin/qemu-hppa-static as binfmt interpreter for hppa
sh: write error: Invalid argument
Setting /qus/bin/qemu-riscv32-static as binfmt interpreter for riscv32
sh: write error: Invalid argument
Setting /qus/bin/qemu-riscv64-static as binfmt interpreter for riscv64
sh: write error: Invalid argument
Setting /qus/bin/qemu-xtensa-static as binfmt interpreter for xtensa
sh: write error: Invalid argument
Setting /qus/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
sh: write error: Invalid argument
sh: write error: Invalid argument
Setting /qus/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /qus/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
sh: write error: Invalid argument
Setting /qus/bin/qemu-or1k-static as binfmt interpreter for or1k
sh: write error: Invalid argument
Setting /qus/bin/qemu-hexagon-static as binfmt interpreter for hexagon
sh: write error: Invalid argument
docker run --rm --privileged aptman/qus:latest -s -- -p
command failed: exit code 1`

what is the problem?

**Comment by ashkulz** [comment]
Is this inside a docker container or is this in a VM / actual hardware?

**Comment by ashkulz** [comment]
Please reopen if you can provide more details.
