### ISSUE TITLE
support AmazonLinux 2022

### ISSUE THREAD

**Issue by altherlex** [wkhtmltopdf/packaging#125]
Tried version `wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm` on AL2022 and it doesn't run:

```bash
$ wkhtmltopdf
wkhtmltopdf: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```

**Comment by ashkulz** [comment]
Is Amazon Linux 2022 out of preview yet? I am not in favor of supporting it till it hits GA, as otherwise binaries built now may not work later. You can feel free to copy the definition for Amazon Linux 2 and tweak it till it works.
