### ISSUE TITLE
Upgrade to OpenSSL 3.0 

### ISSUE THREAD

**Issue by altherlex** [wkhtmltopdf/packaging#126]
wkhtmltopdf uses OpenSSL v1 and has conflict on system with OpenSSL v3 installed.

**Comment by ashkulz** [comment]
Which distro/OS are you talking about?

**Comment by altherlex** [comment]
wkhtmltox-0.12.6-1.amazonlinux2.x86_64

**Comment by ashkulz** [comment]
Duplicate of #125 -- please don't create additional issues, not sure if you saw my comment there?

**Comment by ashkulz** [comment]
If you see the Ubuntu 22.04 build, it does work -- so OpenSSL 3.0 support isn't an issue. You're using a build for AmazonLinux 2 on AmazonLinux 2022 which isn't gonna work.
