### ISSUE TITLE
Hope for Kylin OS V10 build

### ISSUE THREAD

**Issue by CY-Qiu** [wkhtmltopdf/packaging#128]
In china, Kylin OS V10 is becoming a very popular distribution rapidly, especially in arm64 market.
It is a commercial version of Ubuntu Kylin.
See official site: https://kylinos.cn/support/download.html
There are also a docker image in docker hub: https://hub.docker.com/r/freelizhun/kylinosv10

However, when I tried to compile wkhtmltopdf by myself on Kylin OS. I found out even if I use the patched QT, the output pdf's format seems still very different with the windows output pdf, especially in the terms of word place. 

Here is the source html and output pdf.
[wkhtmltopdf_test.zip](https://github.com/wkhtmltopdf/packaging/files/9198745/wkhtmltopdf_test.zip)

**Comment by ashkulz** [comment]
I'm not sure I can help you there, sorry :man_shrugging:
