### ISSUE TITLE
Deb install on Ubuntu should run ldconfig after?

### ISSUE THREAD

**Issue by neocogent** [wkhtmltopdf/packaging#13]
Just installed this on my Mint 19 (Ubuntu 18.04) system and could not get it to work. I was trying to use with a python wrapper. It gave errors related to libwkhtmltox.so.0 not found. After a bit of detective work it turns out that ldconfig needs to be run to update paths after the lib is installed. After doing that the library was found and test code in python using it worked without error.

I wonder if this is something the dpkg install process should do in order to ensure it can be used after installing? Or at least maybe add a line to docs so users aren't scratching their head and wasting time googling to get a working setup.

**Comment by ashkulz** [comment]
Thanks for the report! I guess I need to add [--deb-shlibs](https://github.com/jordansissel/fpm/pull/405) when building the package.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which should have this fixed for all `.deb` packages. Please add a comment if you face any problems :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
