### ISSUE TITLE
qpagesetupdialog_unix.cpp: In constructor 'QPageSetupWidget::QPageSetupWidget(QWidget*)'

### ISSUE THREAD

**Issue by MihailIgk** [wkhtmltopdf/packaging#131]
I have the same problem now

[Support for i386 as a host architecture was dropped in 19.10](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Upgrades_on_i386), so we need amd64 only.
I simply copy-pasted the bionic section and replaced bionic with focal.
`./build docker-images focal-amd64` succeeded, but then the compilation failed with the error:

```
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp: In constructor 'QPageSetupWidget::QPageSetupWidget(QWidget*)':              
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:276:12: error: 'class Ui::QPageSetupWidget' has no member named 'topMargin' 
  276 |     widget.topMargin->setSuffix(suffix);                                                                             
      |            ^~~~~~~~~                                                                                         
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:277:12: error: 'class Ui::QPageSetupWidget' has no member named 'bottomMargin'
  277 |     widget.bottomMargin->setSuffix(suffix);                                                                     
      |            ^~~~~~~~~~~~                                                                                                
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:278:12: error: 'class Ui::QPageSetupWidget' has no member named 'leftMargin'     
  278 |     widget.leftMargin->setSuffix(suffix);                                                                            
      |            ^~~~~~~~~~                                                                                     
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:279:12: error: 'class Ui::QPageSetupWidget' has no member named 'rightMargin'
  279 |     widget.rightMargin->setSuffix(suffix);                                                                           
      |            ^~~~~~~~~~~                                                                                       
```

This is the top of the output, there were many more similar errors.
Could you help please?

_Originally posted by @kraft001 in https://github.com/wkhtmltopdf/packaging/issues/63#issuecomment-626129315_

**Comment by MihailIgk** [comment]
And I have the same proplem on debian 11, trying to execute:
`./build package-docker bullseye-amd64 ..`
and getting errors:
`/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:276:12: error: 'class Ui::QPageSetupWidget' has no member named 'topMargin'
  276 |     widget.topMargin->setSuffix(suffix);
      |            ^~~~~~~~~
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:277:12: error: 'class Ui::QPageSetupWidget' has no member named 'bottomMargin'
  277 |     widget.bottomMargin->setSuffix(suffix);
      |            ^~~~~~~~~~~~
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:278:12: error: 'class Ui::QPageSetupWidget' has no member named 'leftMargin'
  278 |     widget.leftMargin->setSuffix(suffix);
      |            ^~~~~~~~~~
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:279:12: error: 'class Ui::QPageSetupWidget' has no member named 'rightMargin'
  279 |     widget.rightMargin->setSuffix(suffix);
      |            ^~~~~~~~~~~
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:280:12: error: 'class Ui::QPageSetupWidget' has no member named 'paperWidth'
  280 |     widget.paperWidth->setSuffix(suffix);
      |            ^~~~~~~~~~
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:281:12: error: 'class Ui::QPageSetupWidget' has no member named 'paperHeight'
  281 |     widget.paperHeight->setSuffix(suffix);
      |            ^~~~~~~~~~~
/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:283:47: error: 'class Ui::QPageSetupWidget' has no member named 'preview'
  283 |     QVBoxLayout *lay = new QVBoxLayout(widget.preview);
`

**Comment by ashkulz** [comment]
Did you use this [`qt` branch](https://github.com/wkhtmltopdf/qt/commits/wk_4.8.7_0.12.6)? That's what is used for the builds.

**Comment by MihailIgk** [comment]
> Did you use this [`qt` branch](https://github.com/wkhtmltopdf/qt/commits/wk_4.8.7_0.12.6)? That's what is used for the builds.

Oh no, I didn't.. Yes, it works excellent on this branch, thank you so much!
