### ISSUE TITLE
Native arm builds fail

### ISSUE THREAD

**Issue by micchickenburger** [wkhtmltopdf/packaging#132]
Native arm builds fail because `wkhtmltopdf/fpm` docker image on Docker Hub does not have an arm64 platform type.

A workaround was to build locally.

```shell
cd /path/to/wkhtmltopdf/packaging
sudo docker build -t wkhtmltopdf/fpm:1.10.2-20200531 -f docker/Dockerfile.fpm docker/
sudo python3 build --no-qemu package-docker focal-arm64 ../wkhtmltopdf/
```

**Comment by ashkulz** [comment]
@micchickenburger true, I don't have a native ARM machine so that I can push it to `hub.docker.com`. Do you know of a way I can get it working on an amd64 host? If so, I'll be happy to push an updated image.

**Comment by micchickenburger** [comment]
I don't know a way to do that from amd64/x86_64, but I can push the one I built if you'd like.  I think my docker hub ID is the same as my github handle.

**Comment by ashkulz** [comment]
@micchickenburger can you check if it works now? Hopefully the multi-platform build works :crossed_fingers:
