### ISSUE TITLE
Build for bionic and focal amd64

### ISSUE THREAD

**Issue by guoard** [wkhtmltopdf/packaging#137]
Hi,
For version `wkhtmltox_0.12.6.1-2` There is package for `jammy_amd64.deb`.
Is there any reason that you don't build for bionic and focial amd64? or Is it possible to build for those versions?

**Comment by ashkulz** [comment]
There is already a version for those distributions, the only reason 0.12.6.1 exists to fix a build issue with the later distributions :man_shrugging:

**Comment by oyale** [comment]
Hi, sorry to reopen this issue, but....

This selective release of version 0.12.6.1-2 for specific distributions is causing problems with our current deployment mechanism, which is designed to be as distro-agnostic as possible. (It gets the latest version and creates the download URL based on it and the version name).

Is there any chance you would consider releasing version 0.12.6.1-2 for the bionic and focal distributions, even if the changes contained do not affect all of them? If this is not possible, we will understand and restructure our deployment process, no problem.

Thank you for your work and support.
