### ISSUE TITLE
linux 中 'footer-center':'第[page]页，共[topage]页', #设置页码，不支持中文

### ISSUE THREAD

**Issue by gg22mm** [wkhtmltopdf/packaging#138]
down: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.centos7.x86_64.rpm

'footer-center':'第[page]页，共[topage]页', #Chinese is not supported

![微信图片_20230109170029](https://user-images.githubusercontent.com/6648329/211281178-ab3511e1-f011-4ba1-a5d5-fbf935160e26.png)

中文不显示如下：

![微信图片_20230109170050](https://user-images.githubusercontent.com/6648329/211281192-2a2d5ba4-7d4f-47ef-971c-60d336bdce9b.png)

**Comment by ashkulz** [comment]
Sorry, I only understand English. Plus this repository is for packaging and not for general support.

**Comment by gg22mm** [comment]
ok, thank you very much! This project is very good! Hope it can be maintained forever~~
