### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by alekth85** [wkhtmltopdf/packaging#139]
Trying to compile it, but having the same error on all targets. Really would appreciate some hint, since... google is not helpful. Usually it is, but in this case, it's not. Seems only I'm having this problem.

./build compile-docker focal-amd64 /usr/local/src/wkhtmltopdf /usr/local/wkhtmltopdf

This is the build line (all prerequisites are installed via apt)... and this is the error:
/usr/bin/ld: cannot find -lQtWebKit
collect2: error: ld returned 1 exit status
make[1]: Leaving directory '/tgt/app/src/lib'
make[1]: *** [Makefile:166: ../../bin/libwkhtmltox.so.0.12.7] Error 1
make: *** [Makefile:61: sub-src-lib-install_subtargets-ordered] Error 2

The QT in the /usr/local/src/wkhtmltopdf directory I got by:
git clone https://github.com/wkhtmltopdf/qt.git qt

Thanks

**Comment by ashkulz** [comment]
You'll need to use the [`0.12.6.x` branch](https://github.com/wkhtmltopdf/wkhtmltopdf/tree/0.12.6.x), as I think you need those Qt commits to compile.

**Comment by alekth85** [comment]
Yes, that did it. If anybody else have same problem... this worked for me.

Thanks.
