### ISSUE TITLE
add support for Amazon linux distro for lambda

### ISSUE THREAD

**Issue by mmayer1** [wkhtmltopdf/packaging#14]
There's a few people out there using wkhtmltopdf inside Amazon lambdas. It would be awesome to have a single statically linked executable that "just works" in AWS lambda. https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

Vagrant box that appears to be the correct image:
https://app.vagrantup.com/mvbcoding/boxes/awslinux

**Comment by mmayer1** [comment]
Nevermind. I found out using the build from CentOs 6 seems to work.

**Comment by artyomboyko** [comment]
@mmayer1 

Are you using `./build package-docker centos6-x86_64` command ? or custom vagrant target ?

**Comment by mmayer1** [comment]
I think we grabbed this download, and just pulled out the binary from that
https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.centos6.x86_64.rpm

**Comment by stevenspiel** [comment]
https://majestic.cloud/how-to-install-wkhtmltopdf-on-amazon-linux/ was helpful for me

**Comment by ashkulz** [comment]
I'm adding an AmazonLinux2 RPM in the next release, see #66.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has packages for AmazonLinux2. Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
