### ISSUE TITLE
Build for Ubuntu 22.04

### ISSUE THREAD

**Issue by mvl22** [wkhtmltopdf/packaging#141]
Currently the latest build for Ubuntu is for 20.04. 22.04 is now out so would be useful to have that available.

For now, the following is a workaround:

```
# Dependencies
apt-get -y install xfonts-75dpi
wget -P /tmp/ http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
dpkg -i /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
rm /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb

# Add main install
wget -P /tmp/ https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
dpkg -i /tmp/wkhtmltox*.deb
rm /tmp/wkhtmltox*.deb
```

**Comment by ashkulz** [comment]
I'm not sure what you mean -- the builds are listed on the [downloads page](https://wkhtmltopdf.org/downloads), see [the 0.12.6.1-2 release](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6.1-2)

**Comment by mvl22** [comment]
Sorry, I can see it now. I was looking on the GitHub releases page and GitHub seems to hide part of a long list of links by default.
