### ISSUE TITLE
Release for amazonlinux2023

### ISSUE THREAD

**Issue by phuong01nov** [wkhtmltopdf/packaging#144]
[wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm](https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm) is OK for amazonlinux2.
But latest amazonlinux is amazonlinux2023 now.
It occurs error `/usr/local/bin/wkhtmltopdf: error while loading shared libraries: libpng15.so.15: cannot open shared object file: No such file or directory` on amazonlinux2023.
I tried to build wkhtmltopdf for amazonlinux2023 but it occurs error `/src/qt/src/gui/dialogs/qpagesetupdialog_unix.cpp:276:12: error: 'class Ui::QPageSetupWidget' has no member named 'topMargin'...`.
Could you help me to make a release for amazonlinux2023?
Thank you!

**Comment by ashkulz** [comment]
I think you can just rename 2022 => 2023 in c0c9aecde2dcdc4f04004ce2e9ce6463aa54ad2a and it should work.
