### ISSUE TITLE
Consider hosting deb/rpm repos for packages.

### ISSUE THREAD

**Issue by PhonicUK** [wkhtmltopdf/packaging#151]
Right now it's a pain in the butt to ship software that depends on wkhtmltopdf/image because you can't simply add 'wkhtmltopdf' as a package dependency and have an up-to-date version.

You can fetch deb/rpm files - but you have to know ahead of time what the URL is for the latest version.

I'd like to suggest that there is a formal package repository (or a PPA in Ubuntu speak) to accommodate these packages. That way the end user could add the repository to their system, run `apt/yum install wkhtmltopdf` and have it behave correctly, as well as be kept up-to-date.

**Comment by ashkulz** [comment]
@PhonicUK wkhtmltopdf is now obsolete, so it makes no sense to add a repository.

Plus hosting for that would require a separate service rather than github releases.
