### ISSUE TITLE
Is there a 0.12.6.1-2 version for windows?

### ISSUE THREAD

**Issue by lstbrian** [wkhtmltopdf/packaging#152]

**Comment by ashkulz** [comment]
Nope, the 0.12.6 release still works for Windows. A rebuild with updated OpenSSL is ideally required, but the build is broken and I'm not really sure I'll get around to fixing it :man_shrugging:

**Comment by lstbrian** [comment]
> Nope, the 0.12.6 release still works for Windows. A rebuild with updated OpenSSL is ideally required, but the build is broken and I'm not really sure I'll get around to fixing it 🤷‍♂️

oh

is the 0.12.6 the same as 0.12.6.1-2 for windows? 

I am not sure if the 0.12.1-2 would fix some css problems such as grid not displaying after pdf convertion.

**Comment by ashkulz** [comment]
Nope, it's just a release to fix compilation issues with updated Linux distributions.
