### ISSUE TITLE
LCM and HCF type of content is not rendering properly in pdf

### ISSUE THREAD

**Issue by kanchanbartwal** [wkhtmltopdf/packaging#153]
I have used **wkhtmltopdf 0.12.6 (with patched qt)** and **wkhtmltopdf 0.12.5 (with patched qt)** which are installed from following sources
**wkhtmltopdf 0.12.6 :** https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
**wkhtmltopdf 0.12.5 :** https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.focal_amd64.deb

but in both versions whenever I am trying to convert mathml of LCM type content into pdf it did not rendered properly.
my content in html(mathml) is as follows
![Screenshot from 2023-05-08 13-12-33](https://user-images.githubusercontent.com/41582805/236766069-65dd044a-2ef9-494d-b207-3fab1041e5a7.png)

but I am getting pdf output in 2 ways

>  only variable without lines in case of absence of --javascript-delay option (which means default 200ms of javascript-delay).

![Screenshot from 2023-05-08 14-19-23](https://user-images.githubusercontent.com/41582805/236780785-c5d357a8-77ac-4332-9a9e-dd9c017de41f.png)

>  no content only long lines on page when there is --javascript-delay of more than 200 ms.

![Screenshot from 2023-05-08 14-33-25](https://user-images.githubusercontent.com/41582805/236783495-175c6742-e6c0-4d77-bb65-b352f94398ca.png)

In case of unpatched QT versions, This type of content rendered perfectly in pdf but I need to add header-html and footer-html for pdfs that's why I am using "pachted QT" versions
as in normal versions (unpatched QT) I am getting error while converting html to pdf for header and footer htmls.
`The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.Loading page (1/2)`

Please help, I need footers/headers html as well as LCM type content in my pdf.

**Comment by ashkulz** [comment]
Please migrate to a different tool, as wkhtmltopdf is unsupported. Either way, this repo is only for packaging and not general help.

**Comment by kanchanbartwal** [comment]
I am not able to comment or create any issue in https://github.com/wkhtmltopdf/wkhtmltopdf as this is archived by owner.

**Comment by ashkulz** [comment]
Like I said, it is unsupported/EOL.
