### ISSUE TITLE
/src/qt/configure: 149: cmake: not found

### ISSUE THREAD

**Issue by mrskuvare** [wkhtmltopdf/packaging#157]
Hi,

can't build and get `/src/qt/configure: 149: cmake: not found`

`$ sudo python build --use-qemu linux/arm64/v8 package-docker --clean bullseye-arm64 ../.
Untagged: aptman/qus:d5.0
Untagged: aptman/qus@sha256:a3a54558930cc756d424d8b5774b5baafdb8b3851b20d535f621a41e6110b364
Deleted: sha256:00f46e0a64cb47e07de6f158e456c48ee5e98d6410b2df1cade862cd4e0e5b8a
Deleted: sha256:04127179a44ae0cbd8c8a892c506a9d44c3ff02e89139127f986421abe094f9a
Deleted: sha256:34131c56dfeb115fd889245ad7ad29b6188248e27f0675e0e5bcfcdb60e1533a
Deleted: sha256:4a3a0fc3a5b7910ba2d425206f46963e2480d14b7337528e600ed3ad0706937e
Deleted: sha256:743c111ed52501ef6e29029a60ec074733ecc63b46f9f43c4e2fc4e0e88b506b
Deleted: sha256:5727cc0d5aaf44f7fa62137acb2331be871dcd8c9565354ad567d5389be2d819
d5.0: Pulling from aptman/qus
b532f239b6e6: Pull complete 
f3b582a3c47c: Pull complete 
11b3ad36aef2: Pull complete 
4b6cbdc37865: Pull complete 
795da393b8be: Pull complete 
Digest: sha256:a3a54558930cc756d424d8b5774b5baafdb8b3851b20d535f621a41e6110b364
Status: Downloaded newer image for aptman/qus:d5.0
docker.io/aptman/qus:d5.0
cat ./qemu-binfmt-conf.sh | sh -s -- --path=/qus/bin -r
cat ./qemu-binfmt-conf.sh | sh -s -- --path=/qus/bin -p --suffix -static
Setting /qus/bin/qemu-i386-static as binfmt interpreter for i386
Setting /qus/bin/qemu-i386-static as binfmt interpreter for i486
Setting /qus/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /qus/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /qus/bin/qemu-sparc-static as binfmt interpreter for sparc
Setting /qus/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /qus/bin/qemu-sparc64-static as binfmt interpreter for sparc64
Setting /qus/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /qus/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /qus/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /qus/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /qus/bin/qemu-mips-static as binfmt interpreter for mips
Setting /qus/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /qus/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /qus/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /qus/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /qus/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /qus/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /qus/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /qus/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /qus/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /qus/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /qus/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /qus/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /qus/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /qus/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /qus/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /qus/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Setting /qus/bin/qemu-or1k-static as binfmt interpreter for or1k
Setting /qus/bin/qemu-x86_64-static as binfmt interpreter for x86_64
/src/qt/configure: 149: cmake: not found
/src/qt/configure: 166: cmake: not found
make: *** No targets specified and no makefile found.  Stop.
docker run --rm -v/home/me/build/wkhtmltopdf:/src -v/home/me/build/wkhtmltopdf/packaging/targets/bullseye-arm64:/tgt -v/home/me/build/wkhtmltopdf/packaging:/pkg -w/tgt/qt --user 0:0 wkhtmltopdf/0.12:bullseye-arm64 make -j4
command failed: exit code 2`

Can anyone describe what I'm doing wrong?

**Comment by ashkulz** [comment]
Why are you not simply using [this package](https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bullseye_arm64.deb)?

**Comment by mrskuvare** [comment]
Thanks, but that wasn't my question. You can close that here after you have done a useable [README.md](https://github.com/wkhtmltopdf/packaging/issues/157#readme)...
