### ISSUE TITLE
Noob question: how do I build a package for my Linux server?

### ISSUE THREAD

**Issue by salamihawk** [wkhtmltopdf/packaging#158]
Hello,

I understand that this is not an "issue" per se, so I apologize for asking in this manner. I have a web app (Flask-based) running on an Apache server on Debian 11. I generate PDF Reports using wkhtmltopdf, which I installed using the standard apt package. Apparently this was wrong, because I need a patched qt in order to have the headers and footers I want in my PDFs. 

I stumbled upon this repository thinking this is my best chance at actually resolving this issue, but I'm not skilled in packaging at all. So how do I do this?

I installed python3-yaml, docker.io and p7zip-full via apt (I left out vagrant and virtualbox because I don't believe I need them from what I could understand of the main page here). However, I don't know what to do next. It's asking me to run build, which I found to be contained in the packaging archive, but then it's asking me for a path to wkhtmltopdf and I don't know what it wants from me now. Is it asking for the path to the binary? (/usr/bin/wkhtmltopdf) or some source code or something?

Thanks for any help

**Comment by ashkulz** [comment]
@salamihawk please install the package for Debian 11 from the [downloads page](https://wkhtmltopdf.org/downloads.html#stable).
