### ISSUE TITLE
When can we have wkhtmltox-0.13.0-alpha for Mac OS X

### ISSUE THREAD

**Issue by faheemhameed** [wkhtmltopdf/packaging#17]
Hi there,

When can we have wkhtmltox-0.13.0-alpha for Mac OS X?

Many thanks,
Hameed

**Comment by ashkulz** [comment]
I haven't worked on `0.13` in a long time, so not sure of any ETA. It requires porting the `0.12` branch to using the build system for Qt5 (which has a lot of new dependencies).
