### ISSUE TITLE
An Evansport (i686) package of 0.12.1 or 0.12.1.2 or 0.12.1.3 ?

### ISSUE THREAD

**Issue by edoubleoo** [wkhtmltopdf/packaging#18]
HI there, I've been on the hunt for a while for a working 0.12.1 (or 0.12.1.2 or 0.12.1.3) patched with qt and inclusive of its dependencies. It is starting to be my white whale. 

Having tried the majority of the i386 and i686 packages available, I've been left with only partial success and would need a compiled package to complete the installation.

**Comment by ashkulz** [comment]
I think you're looking [for this](https://builds.wkhtmltopdf.org/0.12.1.3/). Let me know if that doesn't work for you.
