### ISSUE TITLE
Suse Linux RPM

### ISSUE THREAD

**Issue by bugsoftware** [wkhtmltopdf/packaging#22]
Hi,

What would be the possibility of compiling, making a build for Suse Linux ? I can provide you platform with SSH if needed.

I am trying without much success.

**Comment by ashkulz** [comment]
Should be straightforward if there's a docker image available: just install the required development libraries and you should be good to go (see Ubuntu / Debian as an example).

**Comment by bugsoftware** [comment]
Unfortunately I tried without much success. I even tried to compile from source using python, both without much success

**Comment by ashkulz** [comment]
What's the exact distro version you were using? See the README for steps on compiling it under Docker.

**Comment by ashkulz** [comment]
Are you interested in packaging for your distro?

**Comment by bugsoftware** [comment]
We essentially use SUSE and I was trying to install it to generate PDFs for a customer. We have gave up because we couldn't install it.

**Comment by ashkulz** [comment]
Without knowing the distro version, I can't really help

**Comment by bugsoftware** [comment]
SLES 15

**Comment by ashkulz** [comment]
What's the nearest equivalent image available on Docker? I could only find [opensuse/leap:15](https://hub.docker.com/r/opensuse/leap).

**Comment by bugsoftware** [comment]
Yep. That's about it. OpenSuse

**Comment by niner** [comment]
I have successfully added support for openSUSE Leap 15.0 in:
https://github.com/niner/packaging/commit/6fab13d06ef88e6eac9e589fc1b552d0f2eb6b27
I'd send a pull request, but Github fails strangely with a 404, so could you please just pull the commit?

**Comment by ashkulz** [comment]
Thanks, @niner! I think you can create a PR [using this link](https://github.com/wkhtmltopdf/packaging/compare/0.12...niner:0.12).

**Comment by diggy128** [comment]
Any chance to have this PR?
And even maybe for OpenSUSE Leap 15.1?

**Comment by ashkulz** [comment]
There was no followup on #27 -- would be great if you can step up in making a PR 👍

**Comment by diggy128** [comment]
I'd most definitely do so but I don't have any knowledge regarding packaging specs. 

When I'll get myself familiar with it I'll give it a try

**Comment by ashkulz** [comment]
@diggy128 @niner @bugsoftware @roebert if I make a package for a new target `opensuse.leap15`, would you be willing to do a quick test for it?

**Comment by diggy128** [comment]
@ashkulz Sure where can I get it?

**Comment by ashkulz** [comment]
@diggy128 I'll probably work on it tomorrow, based on the work @niner did in #27.

**Comment by diggy128** [comment]
OK. Ping me once you are ready and I'll test it.

**Comment by ashkulz** [comment]
@diggy128 can you try to check if this works properly:
```
zypper install -y --allow-unsigned-rpm https://builds.wkhtmltopdf.org/wkhtmltox-0.12.6-0.20200602.27.dev.f1ef81d.opensuse.leap15.x86_64.rpm
```
I built this locally, #68 will do it via Azure Pipelines but may take a _long_ time to complete.

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has RPMs for multiple architectures (x86_64, aarch64 and ppc64le). Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by diggy128** [comment]
Just tested on OpenSuse Leap 15.1
Works smoothly so far.
Just one note: that the binaries are installed at /usr/local/bin instead of /usr/bin used by the mainstream opensuse packages. That is not necessarily bad as it allows to have upstream and mainstream packages installed side by side.

**Comment by bugsoftware** [comment]
It works perfect.

**Comment by ashkulz** [comment]
@diggy128: that's a deliberate decision as these are not supplied by the distribution.
