### ISSUE TITLE
Ubuntu 19 support

### ISSUE THREAD

**Issue by P9GIT** [wkhtmltopdf/packaging#23]
Any plans for a build for Ubuntu 19?

**Comment by ashkulz** [comment]
Doesn't the Ubuntu 18.04 build work?

**Comment by P9GIT** [comment]
@ashkulz 

I get a dependency error when installing https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
on a vanilla Ubuntu Disco Dingo (19) docker image.

```
root@20e23492ffa3:/# dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
Selecting previously unselected package wkhtmltox.
(Reading database ... 64584 files and directories currently installed.)
Preparing to unpack wkhtmltox_0.12.5-1.bionic_amd64.deb ...
Unpacking wkhtmltox (1:0.12.5-1.bionic) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on xfonts-75dpi; however:
  Package xfonts-75dpi is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 wkhtmltox
```

Maybe you or somebody else has encountered this before?
Thanks.

**Comment by ashkulz** [comment]
Just run `apt-get install -f` which should install the missing package.

**Comment by P9GIT** [comment]
Hi @ashkulz 

Just to round this issue up in case others read this.

The real problem is that I did not run apt-get update prior to the install. The dependencies will thereafter be fulfilled when doing "apt-get install ./wkhtmltox_0.12.5-1.bionic_amd64.deb".
Rookie mistake :(
Sorry for bothering you with this.
