### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by jttbharoo** [wkhtmltopdf/packaging#28]
QXcbConnection: Could not connect to display
wkhtmltopdf exited with code 134

in

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by ashkulz** [comment]
Wrong repository, looks like you are not running the distro-provided version.
