### ISSUE TITLE
How to build without patched Qt

### ISSUE THREAD

**Issue by lusinh** [wkhtmltopdf/packaging#31]
I only need some simple function of wkhtmltopdf. My docker wkhtmltopdf work perfectly.
But, with the version with patched Qt downloaded in wkhtmltopdf site, It not work correct, the pdf file broken table border.
In my docker, wkhtmltopdf is reduced version. When I run `wkhtmltopdf -h`, the result is:
```
Name:
  wkhtmltopdf 0.12.5
...
Reduced Functionality:
  This version of wkhtmltopdf has been compiled against a version of QT without
  the wkhtmltopdf patches. Therefore some features are missing, if you need
  these features please use the static version.
```

I need run wkhtmltopdf on centos 6. Thus, I need build my self wkhtmltopdf without patched Qt. How to do this?

p/s: I tried build wkhtmltopdf from this repo. The result is same with download file in main site. #

**Comment by ashkulz** [comment]
Just install the necessary libraries and run `qmake && make`? You can see that it's a tested configuration by looking at [.travis.yml](https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.12.5/.travis.yml#L45). Note that CentOS may have older libraries than what distribution you're using in docker, so the output may or may not be what you want.

**Comment by woodyza** [comment]
Hi! I have this same requirement, but I could use a little more detail on the suggested approach please.

> Just install the necessary libraries and run qmake && make

What environment would this be in; the target Centos distro with the wkhtmltopdf source loaded - i.e. not using the packaging system in this repo?

**Comment by ashkulz** [comment]
@woodyza: you're right, you'll have to install `libqtwebkit5-dev` or equivalent package and just compile like a normal qt5 application.

**Comment by arnaldobadin** [comment]
@ashkulz  I built using `qmake && make`, but when I try to run the wkhtmltopdf in the yielded bin folder, it returns: `./wkhtmltopdf: error while loading shared libraries: libwkhtmltox.so.0: cannot open shared object file: No such file or directory`

But in the bin folder I have this `libwkhtmltox.so.0` together with wkhtmltopdf executable.  Seems odd to me, I can't find a solution :/

**Comment by ashkulz** [comment]
@arnaldobadin I think you need to set `LD_LIBRARY_PATH=<place-where-lib-is> wkhtmltopdf`.

**Comment by arnaldobadin** [comment]
@ashkulz it worked, but now it is asking for a lot of libraries... I am trying to run it on Lambda. Do you know how I can build it without patched Qt?

**Comment by ashkulz** [comment]
@arnaldobadin see [after_compile/amazonlinux2_lambda.sh](https://github.com/wkhtmltopdf/packaging/blob/master/after_compile/amazonlinux2_lambda.sh), you probably need to copy the `libQt` libraries to that list.
