### ISSUE TITLE
build raspbian.stretch-armhf 

### ISSUE THREAD

**Issue by goodforever** [wkhtmltopdf/packaging#32]
Hi I build raspbian.stretch-armhf ,then I got 
./build package-docker raspbian.stretch-armhf  ../wkhtmltopdf
enabling qemu-aarch64 ...cat: write error: Invalid argument
docker run --rm --privileged fkrull/qemu-user-static enable
command failed: exit code 1

**Comment by ashkulz** [comment]
@goodforever: are you running on a machine where you have `sudo` access with kernel 4.8 or above?

**Comment by goodforever** [comment]
@ashkulz I have sudo ,but the kernel maybe not 4.8. 
Thanks!

**Comment by ashkulz** [comment]
@goodforever: please reopen if you get an issue with later kernels, as this is documented in README.
