### ISSUE TITLE
Get the right build for quality documents AND Docker

### ISSUE THREAD

**Issue by stockersky** [wkhtmltopdf/packaging#33]
I recently tried wkhtmltopdf and was very pleased by the result.

I first installed it on my Fedora 30 workstation from Fedora repo : results were perfect and crisp!

Then, I wanted to deploy it on Docker. I first used Alpine Linux. Then, while executing Docker instance on my workstation, I noticed this was not that crisp anymore : images were distorted, etc...

I then deployed on a Docker Debian Buster Stretch and the crispiness was happily back again : Good so far.

But, while deploying on AWS, wkhtmltopdf would generate blank pdf and image... I guess, the reason is that wkhtmltopdf package is not Qt patched... (But why does it work on a docker instance on my workstation?)

So, I installed the Qt Patched package provided here : https://wkhtmltopdf.org/downloads.html

Cool, documents are generated on AWS Docker... But are not crispy at all...
No flexbox!!!

I just applied the packaging procedure described in this repo and got a package for target debian busty amd64 build (checkout with the 012.5 tag). Unfortunately, it's the same problem as above : no flexbox and distorted images... Did not even tried to execute it on AWS Docker...
Well, I guess I just built the same binaries as those provided by your project.

So, the point here is to get - or build - a package that would make crispy documents AND being able to work on Docker...

Are they special arguments to add to build it with more features (flexbox?) ???

Debian and Fedora achieved to build 0.12.5 versions which render great. So, I know this lib is able to do it! Is this achieved by installed additional packages?
I just need the Fedora/Debian packages quality with Docker support (Qt)!!!!

Thanks for your help

**Comment by stockersky** [comment]
I rebuilt, but this time from master. No difference.... 

Alright, I unpacked Fedora RPM and looked at their spec :+1: 
```
%build
%if 0%{?usegitsource} >= 1
cd %{name}-*/
%endif
%if 0%{?fedora} >= 24
%{qmake_qt5}
%else
%{qmake_qt4}
%endif
make %{_smp_mflags}

```

**So, they use qt5.**

But, the build process described here use qt4 https://github.com/wkhtmltopdf/qt (described as forked Qt 4.8 with wkhtmltopdf-specific patches). I did install this with `git clone --recursive`.

Indeed, the documents' crispiness came from qt5. I guess Debian uses the same. Thus, this is why those package had a good rendering. Qt4 won't make it (flexbox and i guess, other things).

So, i'm a bit struggling here...

I found this : https://github.com/wkhtmltopdf/wkhtmltopdf/blob/0.13/README.md#release-plan
But this is from 2015.

There are some project that sound to build wkhtmltopdf from qt5 Patched...
https://github.com/RoseRocket/docker-alpine-wkhtmltopdf-patched-qt

**Comment by stockersky** [comment]
What is the use of Xrfb (virtual xserver for headless server) in wkhtmltopdf?
The wkhtmltopdf Qt4 patched works without it...

While trying with the stock Debian wkhtmltopdf package, I could not make it work with AWS Docker when using Xrfb... Maybe I did it wrong?
```
RUN printf '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltopdf -q $*' > /usr/bin/wkhtmltopdf.sh
RUN chmod a+x /usr/bin/wkhtmltopdf.sh
RUN ln -s /usr/bin/wkhtmltopdf.sh /usr/local/bin/wkhtmltopdf

RUN printf '#!/bin/bash\nxvfb-run -a --server-args="-screen 0, 1024x768x24" /usr/bin/wkhtmltoimage -q $*' > /usr/bin/wkhtmltoimage.sh
RUN chmod a+x /usr/bin/wkhtmltoimage.sh
RUN ln -s /usr/bin/wkhtmltoimage.sh /usr/local/bin/wkhtmltoimage
```

I guess, it worked on my Docker workstation as my host as a GPU and a Xserver started...

**Comment by derek-adair** [comment]
Try this to use xvfb in docker:

```
$>Xvfb :99 &
$>export DISPLAY=:99
```

**Comment by ashkulz** [comment]
Effectively, you're asking for a `0.13` build which uses the latest WebKit engine. There's no such thing as that, I'm afraid -- I've yet to port the patches to the latest QtWebKit release.

I'm going to close the issue for now, I'm planning to post a project status update along with the upcoming `0.12.6` release.
