### ISSUE TITLE
Synology ipkg package

### ISSUE THREAD

**Issue by hkalman** [wkhtmltopdf/packaging#34]
Hello,

I would like to ask you to create ipkg packages for Synology Diskstations too when you create a new release.

Thanks

**Comment by ashkulz** [comment]
@hkalman I'm not sure how to prepare them, are they supported by `fpm`?

**Comment by ludimassa** [comment]
no synology don't have fpm by default

It is very important also for my project install it on synology!

An alternative way is install docker on synology but I don't like this solutions

**Comment by icaroscherma** [comment]
I don't think this is going to be an easy thing to do natively.
Synology DSM 6.2.x (latest stable today) uses Linux kernel 4.4.59 and uses a proprietary package system, it doesn't use `apt`, `pacman`.
By having the x86-64 compiled package it's missing `libXrender1` (and maybe other libraries).
I think the best approach would be to use Docker.

Some other links with people having the same issue (for recent Synology DSM):
- https://community.synology.com/enu/forum/17/post/91782
- https://community.synology.com/enu/forum/10/post/131493
- https://github.com/polo2ro/imapbox/issues/14

**Comment by ashkulz** [comment]
If there is an image available on DockerHub which allows you to install all the libraries, you can try to port it similarly to the support for other OS/architectures. Otherwise, I think @icaroscherma's suggestion to just use `docker` makes the most sense :smile:
