### ISSUE TITLE
Please publish debian buster build for 0.12.5

### ISSUE THREAD

**Issue by fsateler** [wkhtmltopdf/packaging#36]
Hi,

Commit https://github.com/wkhtmltopdf/packaging/commit/66ddc3ee345226521cf037bd5f85089008abb8c0 added support for building on debian buster, which is the current debian stable release. However, such a build does not exist on the homepage yet:

![image](https://user-images.githubusercontent.com/1322013/66850931-22190d00-ef50-11e9-804e-a3c43bdcd6a4.png)

It would be awesome if such a binary would be published.

Thank you for all your great work!

**Comment by ashkulz** [comment]
I believe the `stretch` build should work on `buster`, although I do agree this is pending :+1:

**Comment by stephengtuggy** [comment]
> I believe the `stretch` build should work on `buster`, although I do agree this is pending 👍

I'm not so sure that it works on buster.

I have a copy of the .deb file built for `buster` using the provided build system. I can provide it if the wkhtmltopdf maintainers want me to.

**Comment by stephengtuggy** [comment]
Exact filename: `wkhtmltox_0.12.5-1.buster_amd64.deb`

**Comment by stanleyk** [comment]
Hi, I am not able to build it for buster because of the missing Docker image tagged `0.12_buster-amd64`, are you going to add it anytime soon? Thanks.

@stephengtuggy Would you be so kind to share the build with me? How did you build it? Thank you!

**Comment by ashkulz** [comment]
I haven't got around to building it yet, but you should be able to build the docker image locally using `./build docker-images buster-amd64` and then running the `./build package-docker` command.

**Comment by ashkulz** [comment]
Done, see wkhtmltopdf/wkhtmltopdf@57c23e0 -- sorry for the delay!
