### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by werddomain** [wkhtmltopdf/packaging#39]
Is there an easy way to port this to .net core?

I have see some wrapper for .net Framework. (TuesPechkin is verry nice).

.net core aim to be for all platforms, so if you can target .net standard 2.0, we will be able to use this on MacOs, Android, IOS, Asp.Net Core, Windows Applications, Linux, etc ...

Is there anny work in progress ?

**Comment by ashkulz** [comment]
It would be better to ask this question in the TuesPechkin repository.
