### ISSUE TITLE
Request build for CentOS 8

### ISSUE THREAD

**Issue by dnorgaard-usgs** [wkhtmltopdf/packaging#40]

**Comment by pedrofurtado** [comment]
@marciojg @willradi @ashkulz 👍

**Comment by ashkulz** [comment]
If someone has time, it should be very easy to create a CentOS 8 build -- just modifying the template for earlier releases in `build.yml` should be enough, I think. PRs are welcome :grin:

**Comment by ashkulz** [comment]
@pedrofurtado: apparently, the 32-bit build fails hence I've removed it in defce5220ebc1d90db0fe49dc8fc14e5b1c6d799 -- should've checked before merging :see_no_evil:

**Comment by pedrofurtado** [comment]
@ashkulz Thanks for feedback! 🤝

**Comment by ashkulz** [comment]
Done, see wkhtmltopdf/wkhtmltopdf@57c23e0 -- sorry for the delay!

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
