### ISSUE TITLE
Build command doesn't work as expected

### ISSUE THREAD

**Issue by matthewblott** [wkhtmltopdf/packaging#41]
I ran the command to build for Linux as instructed [here](https://github.com/wkhtmltopdf/packaging/issues/7) but I get an error telling me there are too few arguments.

```
./build package-docker
```

I don't really understand the instructions on the home page either. I've had a look at the ```.yml``` file where it says there are instructions but it isn't at all clear to me what commands I would run for a specific build. I would expect something like the following.

```
./build --target bionic-amd64
```
To get round my use case I've downloaded the previous version directly like so.

```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
```
As I've seen mentioned elsewhere this was a lot simpler but I'm now stuck on an older version as these packages are no longer provided. Any help appreciated :-)

**Comment by ashkulz** [comment]
So if you run it you get
```
./build package-docker
usage: build package-docker [-h] [--clean] [--iteration ITERATION]
                            target src_dir
build package-docker: error: too few arguments
```
I think that's pretty clear to me, you need to run something like (assuming source is in `~/wkhtmltopdf`)
```
./build package-docker bionic-amd64 ~/wkhtmltopdf
```

**Comment by ashkulz** [comment]
I'd appreciate a PR with suggested changes in help text, thanks!

**Comment by stephengtuggy** [comment]
@ashkulz Can this issue be reopened?

I'd be happy to provide a PR with suggested changes to help text. I just want to be sure that my understanding is correct before I do.

Seems to me that the main additional point that needs to be mentioned, is that there are 4 different `./build` commands, and they have to be run in order. You can see these 4 different subcommands when you run `./build` by itself. The second form of `./build` depends on the first, the third form depends on the second, and so on. Also, you have to run each of these `./build` commands for either the same (desired) target, or all targets.

The final point I would make is that the finished build artifact (.deb, .rpm, etc.) is stored back on the main system's storage, not (just) inside the Docker container(s). So it's actually pretty easy to get to.

Is all of this correct?

Thanks!

**Comment by ashkulz** [comment]
@stephengtuggy it's always better to discuss over concrete examples, so a PR would always be welcome!

Regards the build commands, `docker-images` doesn't need to be run (they're published at [DockerHub](https://hub.docker.com/r/wkhtmltopdf/packaging/tags)) and if you use the latter commands they call their dependents (e.g. `package-docker` calls `compile-docker`; `release` calls `package-docker` and `vagrant` as appropriate).

The last point is correct; I do talk about it being available but maybe that needs to be more explicit 🤷‍♂ 

I'm also thinking of switching to automated building of packages via Azure Pipelines, which uses all this under the hood and makes releases as simple as tagging it 🤞

**Comment by stephengtuggy** [comment]
@ashkulz Cool. Thanks for the clarification! I will try to put together an actual PR sometime in the next few days.
