### ISSUE TITLE
Lambda function convert HTML to PDF using wkhtmltopdf failed after upgraded the runtime from Node.js 8.10 to 10.x deployed on Amazon Linux 2

### ISSUE THREAD

**Issue by joechwong** [wkhtmltopdf/packaging#42]
Error happened after deployed to AWS (new AWS Linux 2 with node.js 10.x runtime). It was working with node.js 8.10 runtime with previous AWS Linux.

**Description**
Due to end of life support of Node.js 8.10 runtime for AWS Lambda function, we are currently undergoing an upgrade to Node.js 10.x runtime which runs on a new version of Amazon Linux called the Amazon Linux 2.

Once deployed my application to AWS, I received the following errors:
Error: wkhtmltopdf: error while loading shared libraries: libXrender.so.1: cannot open shared object file: No such file or directory
wkhtmltopdf exited with code 127
at handleError (/var/task/payment/index.js:3715:16)
at ChildProcess. (/var/task/payment/index.js:3683:7)
at ChildProcess.emit (events.js:198:13)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

wkhtmltopdf module depends on libXrender.so system module, which is not included in the Amazon Linux 2 AMI. It worked earlier as this module was available in previous Amazon Linux AMI with Node.js 8.10. 

Are you able to provide a build package compiled with the wkhtmltopdf binary? I can then create a lambda layer from it. 

Thanks
Joe

**Comment by ashkulz** [comment]
Not sure if you saw [my comment here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4523#issuecomment-552774187) -- it looks like a package is missing?

**Comment by joechwong** [comment]
> Not sure if you saw [my comment here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4523#issuecomment-552774187) -- it looks like a package is missing?

Yeah thanks, I saw that. But I need to take a pause in looking further.  Will come back later on. Thanks again.

**Comment by ashkulz** [comment]
Cool, please reopen this issue if you find it's something else.

**Comment by ashkulz** [comment]
An AmazonLinux2 RPM will be part of the upcoming 0.12.6 release (see #66)

**Comment by ashkulz** [comment]
Please see the [latest release](https://github.com/wkhtmltopdf/packaging/releases) which has packages for both multiple targets (x86_64, aarch64). Please add a comment if you face any problems in using the packages :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by jeremymoritz** [comment]
@ashkulz , Is there any way i could pay you to help me fix my AWS lambda upgrade problem?  It was working fine in NodeJS 8.10, but after upgrading to NodeJS 12.10, it's broken, and i have been working on it all day today.  I can get wkhtmltopdf to run without any params (showing the help content), but when i add params, i get an error code.  i appreciate your making the rpm, but I don't understand how to use an rpm or where to put it once i've downloaded it.

**Comment by ashkulz** [comment]
Did you try the [instructions linked from this FAQ entry](https://wkhtmltopdf.org/downloads.html#how-do-i-use-it-with-faas-setups)?

**Comment by jeremymoritz** [comment]
@ashkulz Yes sir.  I read them over a dozen times and attempted to carefully follow every item on the list.  I got a successful lambda layer following those instructions, but when i try to run it with the real html and options, i get error code 1.  I'm at a loss as to what more i can do to make this work.

**Comment by hazi-tgi** [comment]
![image](https://github.com/wkhtmltopdf/packaging/assets/110443138/937edf57-67b5-4c60-ab3c-02c37321d6fa)


serverless.yml 

  wkhtmltopdf-handler:
    handler: api/template.wkhtmltopdfHanlder
    name: wkhtmltopdfHanlder-${self:provider.stage}
    timeout: 300
    runtime: nodejs14.x
    layers:
      - { Ref: WkhtmltoxLayerLambdaLayer }
    environment:
      FONTCONFIG_PATH: /opt/fonts

layers:
  wkhtmltoxLayer:
    name: wkhtmltox
    description: wkhtmltox binaries for pdf/image generation
    package:
      artifact: wkhtmltox-0.12.6-4.amazonlinux2_lambda.zip



# The pdf is broken while running on Lambda, but it's working fine on my local PC.
