### ISSUE TITLE
Build for Raspberry Pi / ARM

### ISSUE THREAD

**Issue by luca-vercelli** [wkhtmltopdf/packaging#44]
Hello,
I would like to know what is (if any) the roadmap to build wkhtmltox for Raspbian (Raspberry Pi, ARM processor).

See e.g.
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1868
and https://github.com/odoo/odoo/issues/1093

I cannot find any "official" documentation.

My use case is for Odoo on Raspbian.

Regards.

**Comment by luca-vercelli** [comment]
Sorry, I didn't realize the package already exists:

https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.raspbian.stretch_armhf.deb

I close the issue.

**Comment by ashkulz** [comment]
@luca-vercelli: there's no `buster` image -- do you need one? Also, I see that the docker repo has changed to https://hub.docker.com/r/balenalib/rpi-raspbian -- would you be willing to test new builds, both for `stretch` and `buster`?

**Comment by luca-vercelli** [comment]
At the moment I don't need that. I'm trying to use the stretch package.

**Comment by ashkulz** [comment]
@luca-vercelli: let me know if it works, I may ask you try another build with the new docker image linked above sometime next week :grin:

**Comment by luca-vercelli** [comment]
Yes, it works great!
Let me know if and how I could test the new build (I am using Raspbian GNU/Linux 10)

**Comment by ashkulz** [comment]
@luca-vercelli: would you be able to basic testing once I implement #50?

**Comment by luca-vercelli** [comment]
@ashkulz what do you need exactly? If you can generate a new package, I could install it and try it.

**Comment by ashkulz** [comment]
That's what I need, basically! Will try to produce it in a day or two 👍

**Comment by luca-vercelli** [comment]
@ashkulz any nes about the Buster package?

**Comment by ashkulz** [comment]
@luca-vercelli: I haven't had time to debug it, unfortunately. There is some difference in the distributions which causes it to skip building WebKit even though it's configured on `buster`.

**Comment by luca-vercelli** [comment]
There's anything I can do? Any log file to read?

**Comment by ashkulz** [comment]
I've triggered a build on the PR, let's see if it works now 🤷‍♂
