### ISSUE TITLE
SRPMs may be missing

### ISSUE THREAD

**Issue by bish0polis** [wkhtmltopdf/packaging#45]
Hi.  I didn't see any SRPMs anywhere.  Please, if the readme.md is missing it, can it please be added?

**Comment by ashkulz** [comment]
It uses [`fpm`](https://github.com/jordansissel/fpm) to be build the RPMs directly, so there isn't a SRPM at all.

**Comment by bby-bishopclark** [comment]
That's a pedigree/provenance concern.  Thanks, though.
