### ISSUE TITLE
YUM repo may be missing

### ISSUE THREAD

**Issue by bish0polis** [wkhtmltopdf/packaging#46]
I also did not notice the yum repo URL in the readme.md file.  Please, can this be added to documentation?

**Comment by ashkulz** [comment]
There isn't a repo URL, you have to download the RPM and install it directly.

**Comment by bby-bishopclark** [comment]
AH.  Supply chain issues, then.  Thanks!  :-/

**Comment by bish0polis** [comment]
I grabbed it from EPEL.  SO easy.  :-|
