### ISSUE TITLE
Checksum for buster missing from SHA256SUMS

### ISSUE THREAD

**Issue by BiggerNoise** [wkhtmltopdf/packaging#47]
The SHA256SUMS file does not contain a signature for debian 10/buster (wkhtmltox_0.12.5-1.buster_amd64.deb).

**Comment by BiggerNoise** [comment]
Ouch. Thanks for the reply though. I'm not real familiar with releasing signed downloads, so I haven't got any suggestions to offer.

Feel free to close this if you like. You might keep it open just so you don't keep getting duplicates.

And thanks for maintaining wkhtmltopdf!

**Comment by ashkulz** [comment]
I'm planning to release `0.12.6` this, so that may be moot. I'll keep this open till that's released :+1:

**Comment by ashkulz** [comment]
See #49 -- I'm hoping to have all packages be generated automatically from a signed commit, so I'm not sure it makes sense to keep a `SHA256SUMS` around 🤷‍♂
