### ISSUE TITLE
Let's Encrypt certificate has expired

### ISSUE THREAD

**Issue by matelau** [wkhtmltopdf/packaging#48]
I'm getting the following error when attempting to apt-get on Ubuntu Docker Image...

```
--2020-01-17 01:09:42--  https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
Resolving downloads.wkhtmltopdf.org (downloads.wkhtmltopdf.org)... 107.174.217.167
Connecting to downloads.wkhtmltopdf.org (downloads.wkhtmltopdf.org)|107.174.217.167|:443... connected.
ERROR: cannot verify downloads.wkhtmltopdf.org's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to downloads.wkhtmltopdf.org insecurely, use `--no-check-certificate'.
```

Command being run
 wget -O wkhtmltopdf.deb https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb     && dpkg -i wkhtmltopdf.deb     && rm wkhtmltopdf.deb

I'm aware of the `--no-check-certificate` option. I just thought I would raise awareness of the issue.

**Comment by ashkulz** [comment]
See wkhtmltopdf/wkhtmltopdf#4586 -- it was fixed almost 17 hours ago. Are you still facing this issue?

**Comment by ashkulz** [comment]
Please reopen if you are facing an issue.
