### ISSUE TITLE
rework Raspberry Pi build

### ISSUE THREAD

**Issue by ashkulz** [wkhtmltopdf/packaging#50]
The docker repository used for the Stretch build [has been deprecated](https://hub.docker.com/r/resin/rpi-raspbian). We need to investigate whether the [new repository](https://hub.docker.com/r/balenalib/rpi-raspbian) generates usable packages, and merge them if we're able to get feedback whether they work.

We should also probably add a `buster` build as well.

**Comment by ashkulz** [comment]
@GM-Script-Writer-62850 @luca-vercelli: can you try if the [dev snapshot](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-dev-20200124) works for you? The `buster` build failed, not sure why -- I don't think I'll have time to debug this in the near future, unfortunately.

**Comment by luca-vercelli** [comment]
@ashkulz I have installed the new package and I printed a pair of invoices with Odoo. Package seems to work as expected.

**Comment by ashkulz** [comment]
Thanks for the confirmation, @luca-vercelli! I've merged the stretch changes, still need to work on the `buster` build hence leaving this issue open.

**Comment by GM-Script-Writer-62850** [comment]
> Distributor ID:	Raspbian
> Description:	Raspbian GNU/Linux 9.4 (stretch)
> Release:	9.4
> Codename:	stretch
Installed with: 
`sudo apt install ./wkhtmltox_0.12.6-0.20191125.22.dev.2a5f250.raspbian.stretch_armhf.deb`
ran with:
`/usr/local/bin/wkhtmltopdf --print-media-type /tmp/General\ Purpose\ Invoice.html test.pdf`
seems fine to me

**Comment by Lonerider2010** [comment]
Running a Raspberry Pi 4 as a PC, I would like to use wkhtmltopdf. In fact there is a wkhtmltopdf package in Raspbian Buster, which comes from Debian (see https://packages.debian.org/buster/wkhtmltopdf), but this is with unpatched qt. So I can't use `--header-html`, for example.
Therefor I would be really interested in the Buster version of wkhtmltopdf (qt patched version).

**Comment by luca-vercelli** [comment]
The package you are looking for should already exist:

https://github.com/wkhtmltopdf/wkhtmltopdf/releases

**Comment by Lonerider2010** [comment]
That is for Raspbian Stretch, but not for Raspbian Buster. But on Raspberry Pi 4 I can run only the Buster version.

**Comment by luca-vercelli** [comment]
I am using the Stretch package on Raspbian 10 (which should be Buster, doesn'it?), and I have no issues.

**Comment by Lonerider2010** [comment]
Thanks for this hint, @luca-vercelli. Was a bit confused by the package name wkhtmltox, which implied to me, that the command name has changed, too. So yes, I can use the qt patched version now.
@ashkulz: please rename the release to show that it is valid for Buster, too.

**Comment by ashkulz** [comment]
@GM-Script-Writer-62850 @luca-vercelli @Lonerider2010: can either of you confirm that [this package for Buster](https://builds.wkhtmltopdf.org/wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb) installs and works on a Raspberry Pi? I was unable to figure out what the issue was in compilation, so produced it via a hack.

**Comment by GM-Script-Writer-62850** [comment]
This is on a Pi0 acting as a usb network gadget and does not have internet access, so to get the dependencies i grabbed them from http://raspbian.raspberrypi.org/raspbian/pool/main/ and scped them over, maybe i did something wrong?
*My other Pis are running jessie and stretch still
```
~$ ssh pi@192.168.5.2
The authenticity of host '192.168.5.2 (192.168.5.2)' can't be established.
ECDSA key fingerprint is SHA256:MtGJl0/iEP2T6iXrD8UQv9XcO4xEj/9IR6aA4wz4Jck.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.5.2' (ECDSA) to the list of known hosts.
pi@192.168.5.2's password: 
Permission denied, please try again.
pi@192.168.5.2's password: 
Linux raspberrypi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Feb 13 16:47:24 2020 from 192.168.5.3

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

rfkill: cannot open /dev/rfkill: Permission denied
rfkill: cannot read /dev/rfkill: Bad file descriptor
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@raspberrypi:~ $ sudo dpkg -i /tmp/wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb 
Selecting previously unselected package wkhtmltox.
(Reading database ... 153919 files and directories currently installed.)
Preparing to unpack .../wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb ...
Unpacking wkhtmltox (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on xfonts-75dpi; however:
  Package xfonts-75dpi is not installed.
 wkhtmltox depends on xfonts-base; however:
  Package xfonts-base is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 wkhtmltox
pi@raspberrypi:~ $ cat /etc/apt/sources.list
deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
pi@raspberrypi:~ $ sudo dpkg -i /tmp/xfonts-75dpi_1.0.3_all.deb 
Selecting previously unselected package xfonts-75dpi.
(Reading database ... 153934 files and directories currently installed.)
Preparing to unpack .../tmp/xfonts-75dpi_1.0.3_all.deb ...
Unpacking xfonts-75dpi (1:1.0.3) ...
Setting up xfonts-75dpi (1:1.0.3) ...
Processing triggers for fontconfig (2.13.1-2) ...
pi@raspberrypi:~ $ sudo dpkg-reconfigure 
/usr/sbin/dpkg-reconfigure: please specify a package to reconfigure
pi@raspberrypi:~ $ sudo dpkg-reconfigure wkhtmltox 
/usr/sbin/dpkg-reconfigure: wkhtmltox is broken or not fully installed
pi@raspberrypi:~ $ sudo dpkg -i /tmp/wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb 
(Reading database ... 154306 files and directories currently installed.)
Preparing to unpack .../wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb ...
Unpacking wkhtmltox (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) over (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) ...
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on xfonts-base; however:
  Package xfonts-base is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 wkhtmltox
pi@raspberrypi:~ $ curl www.google.com
^C
pi@raspberrypi:~ $ sudo dpkg -i /tmp/xfonts-base_1.0.5_all.deb 
Selecting previously unselected package xfonts-base.
(Reading database ... 154306 files and directories currently installed.)
Preparing to unpack /tmp/xfonts-base_1.0.5_all.deb ...
Unpacking xfonts-base (1:1.0.5) ...
Setting up xfonts-base (1:1.0.5) ...
Processing triggers for fontconfig (2.13.1-2) ...
pi@raspberrypi:~ $ sudo dpkg -i /tmp/wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb 
(Reading database ... 154721 files and directories currently installed.)
Preparing to unpack .../wkhtmltox_0.12.6-0.20200528.27.dev.f1ef81d.buster_armhf.deb ...
Unpacking wkhtmltox (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) over (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) ...
Setting up wkhtmltox (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) ...
Processing triggers for man-db (2.8.5-2) ...
pi@raspberrypi:~ $ wkhtmlto
wkhtmltoimage  wkhtmltopdf    
pi@raspberrypi:~ $ wkhtmltopdf /tmp/General\ Purpose\ Invoice.html 
Illegal instruction
pi@raspberrypi:~ $ wkhtmltopdf --help
Illegal instruction
pi@raspberrypi:~ $
```

**Comment by ashkulz** [comment]
@GM-Script-Writer-62850: I compiled this with plain vanilla Debian on `armhf`, which won't work with the Pi Zero [which uses the `armel` instruction set](https://wiki.debian.org/RaspberryPi#Raspberry_Pi_1_.28A.2C_B.2C_A.2B-.2C_B.2B-.2C_Zero.2C_Zero_W.29) -- so you'll have to try it on Pi2+. I think Raspbian includes backward compatibility in their toolchain, hence it works across all Pi hardware versions.

I'm trying to simplify the build process for the upcoming release, guess it won't work for Raspbian -- which I'll have to treat differently than Debian 😞

**Comment by GM-Script-Writer-62850** [comment]
the newest pi i have is the one with 300Mbit network and a quad core(hardware rev. a020d3, i think that is 3b+), that one is running stretch

I have a few 0s (with with no camera, one with a camera, and one with bluetooth), an A+, a B+, a B, and a 3B+

i have not been interested in the new Pis with more cpu and ram, only reason i upgraded from a b+ was the network speed, I even had problems cause it was a quad core cause apparently you can't have 2 commands go to the GPIO at the same time, managed to workaround this by making all my scripts run on the same core

**Comment by ashkulz** [comment]
@luca-vercelli @Lonerider2010: can you try the Raspberry Pi builds (both Stretch and Buster) for the [latest snapshot](https://github.com/wkhtmltopdf/packaging/releases)? So I ultimately found out why the buster build was failing -- see RPi-Distro/pi-gen#271 for details, it was ultimately a [qemu bug](https://bugs.launchpad.net/qemu/+bug/1805913) which needed to be worked around as it hasn't yet been fixed.

This time it's a real RaspberryPi OS build, should work on all hardware revisions -- unlike the last time, @GM-Script-Writer-62850 😁

**Comment by GM-Script-Writer-62850** [comment]
```
pi@raspberrypi:/tmp $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
pi@raspberrypi:/tmp $ apt-cache policy wkhtmltopdf      wkhtmltopdf-dbg  wkhtmltox
wkhtmltopdf:
  Installed: (none)
  Candidate: 0.12.3.2-3
  Version table:
     0.12.3.2-3 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
wkhtmltopdf-dbg:
  Installed: (none)
  Candidate: 0.12.3.2-3
  Version table:
     0.12.3.2-3 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
wkhtmltox:
  Installed: 1:0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.stretch
  Candidate: 1:0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.stretch
  Version table:
 *** 1:0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.stretch 100
        100 /var/lib/dpkg/status
pi@raspberrypi:/tmp $ wkhtmltopdf --version
wkhtmltopdf 0.12.6-dev (with patched qt)
pi@raspberrypi:/tmp $ wkhtmltopdf --print-media-type  ./General\ Purpose\ Invoice.html General\ Purpose\ Invoice.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done 
```
output file looks good

**Comment by GM-Script-Writer-62850** [comment]
```
sudo dpkg -i /tmp/wkhtmltox_0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.buster_armhf.deb 
(Reading database ... 154721 files and directories currently installed.)
Preparing to unpack .../wkhtmltox_0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.buster_armhf.deb ...
Unpacking wkhtmltox (1:0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.buster) over (1:0.12.6-0.20200528.27.dev.f1ef81d.buster) ...
Setting up wkhtmltox (1:0.12.6-0.20200602.27.dev.f1ef81d.raspberrypi.buster) ...
Processing triggers for man-db (2.8.5-2) ...
pi@raspberrypi:~ $ wkhtmltopdf --version
wkhtmltopdf 0.12.6-dev (with patched qt)
pi@raspberrypi:~ $ cd /tmp
pi@raspberrypi:/tmp $ wkhtmltopdf --print-media-type  ./General\ Purpose\ Invoice.html General\ Purpose\ Invoice.pdf
Loading pages (1/6)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done

```
output file looks good

**Comment by ashkulz** [comment]
Thanks for the confirmation, @GM-Script-Writer-62850! I've already merged the PR :+1:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.

**Comment by luca-vercelli** [comment]
@ashkulz I installed the "buster" package yesterday, and I have no issues so far.
