### ISSUE TITLE
Can we have a static latest version of wkhtmltox?

### ISSUE THREAD

**Issue by sxiii** [wkhtmltopdf/packaging#53]
I'm trying to make it work on a system that allows either use static builds or building from source; but building from source of this thing is way too long & hard because of the qt-related issues. Is it possible to get static binaries?

**Comment by ashkulz** [comment]
What is the target platform you're trying to use it on?

**Comment by sxiii** [comment]
@ashkulz JLinux: https://jcloud.no -> it's a source-based distro that mostly use compiled-in software just like Gentoo probably.

**Comment by ashkulz** [comment]
I'm not sure what's the problem in building from source -- if you want to use the unpatched Qt5 binaries, it's a very quick build. For the patched Qt4 build, it's extensively documented via `build.yml` -- if you face problems in getting it to compile, please comment over here.

**Comment by derek-adair** [comment]
Seems VERY counter-intuitive to _require_ a build in a world with docker.  Why not release a static docker version.  Let users docker pull wkhtmltopdf.

It's not working out of the box on xenial:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

```
$>apt list | grep 'docker.io\|python-yaml\|p7zip-full'                                                              
docker.io/xenial-updates,xenial-security 18.09.7-0ubuntu1~16.04.5 amd64
p7zip-full/xenial-updates,xenial-security,now 9.20.1~dfsg.1-4.2ubuntu0.1 amd64 [installed]
python-yaml/xenial,now 3.11-3build1 amd64 [installed]
```

Build error:

```
./build docker-images xenial-amd64                                                                                            1 ↵  10080  14:07:21
enabling qemu-aarch64 ...cat: write error: Invalid argument
docker run --rm --privileged fkrull/qemu-user-static enable
command failed: exit code 1

**Comment by derek-adair** [comment]
>If you're building for other architectures, if there is a docker image then you can use emulation via qemu to use it directly -- but please note that it will be very slow -- it is not uncommon for builds to take 8+ hours on a recent machine.

Again, why not just bake this bad boy into docker?

**Comment by ashkulz** [comment]
@derek-adair: this repo is for _building_ packages, not _using_ them -- it does use docker (and vagrant where appropriate)! Also, I think you haven't read the README, which clearly says:
> Linux kernel >= 4.8 (for linux targets -- foreign archs only) 
> [...]
> On Ubuntu 18.04, this can be installed via a single command:

**Comment by derek-adair** [comment]
Ah yes, I am a dumbo.  Was simply looking for a docker image and misunderstood this projects purpose...

Is there any endorsed effort to Dockerize this wkhtmltopdf?

Also genuine question here: Whats the point of this level of build support with the current VM/Container trends going on?

**Comment by derek-adair** [comment]
It'd also probably be possible for these docker images to be used as run-able versions or spit out binaries.

**Comment by ashkulz** [comment]
Not everyone can use docker directly, wkhtmltopdf is embedded in a lot of applications which themselves use docker for packaging -- so it supports installation on a lot of common supported OSes. You're free to pick your preferred OS 👍

**Comment by derek-adair** [comment]
Ya that makes sense! Probably especially for non-web-apps.

**Comment by ashkulz** [comment]
Closing the issue as original reporter (@sxiii) hasn't responded yet.
