### ISSUE TITLE
Please create build for Ubuntu 19.10 with patched Qt

### ISSUE THREAD

**Issue by chrisc0** [wkhtmltopdf/packaging#54]
Please create build for Ubuntu 19.10 with patched Qt.  Thank you

**Comment by ashkulz** [comment]
@chrisc0: does the Ubuntu 18.04 package not work? I'm not really interested in supporting a distribution which will be EOL very soon, I'd rather wait and support 20.04 LTS

**Comment by chrisc0** [comment]
Yes, that works! I didn't even think to try and use the old version.  Thanks
