### ISSUE TITLE
Build for centOS 7 

### ISSUE THREAD

**Issue by keshcode** [wkhtmltopdf/packaging#55]
I am trying to build binary for centOS7 . can any help ? i cannot upgrade docker version in env to the mentioned version. Is there any other way to build it .

**Comment by ashkulz** [comment]
You can build the binary on any machine, `docker` doesn't need be present on the deployment host. Also, there's a CentOS 7 RPM in the [the latest dev snapshot](https://github.com/wkhtmltopdf/packaging/releases).

**Comment by keshcode** [comment]
i am getting this error 
`[Prism-pro-vm@Prism-pro-vm packaging]$ python build compile-docker centos7-x86_64 wkhtmltopdf build1
docker - version 1.5
Copyright 2003, Ben Jansens <ben@orodu.net>

Usage: docker [OPTIONS]

Options:
  -help             Show this help.
  -display DISLPAY  The X display to connect to.
  -border           The width of the border to put around the
                    system tray icons. Defaults to 1.
  -vertical         Line up the icons vertically. Defaults to
                    horizontally.
  -wmaker           WindowMaker mode. This makes docker a
                    fixed size (64x64) to appear nicely in
                    in WindowMaker.
                    Note: In this mode, you have a fixed
                    number of icons that docker can hold.
  -iconsize SIZE    The size (width and height) to display
                    icons as in the system tray. Defaults to
                    24.
docker run --rm -v/home/Prism-pro-vm/test/packaging/wkhtmltopdf:/src -v/home/Prism-pro-vm/test/packaging/build1:/tgt -w/tgt/qt --user 14805:10000 quay.io/wkhtmltopdf/packaging:0.12_centos7-x86_64 /src/qt/configure -opensource -confirm-license -fast -release -static -graphicssystem raster -webkit -exceptions -xmlpatterns -system-zlib -system-libpng -system-libjpeg -no-libmng -no-libtiff -no-accessibility -no-stl -no-qt3support -no-phonon -no-phonon-backend -no-opengl -no-declarative -no-script -no-scripttools -no-sql-ibase -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-mmx -no-3dnow -no-sse -no-sse2 -no-multimedia -nomake demos -nomake docs -nomake examples -nomake tools -nomake tests -nomake translations -silent -xrender -largefile -iconv -openssl-linked -no-javascript-jit -no-rpath -no-dbus -no-nis -no-cups -no-pch -no-gtkstyle -no-nas-sound -no-sm -no-xshape -no-xinerama -no-xcursor -no-xfixes -no-xrandr -no-mitshm -no-xinput -no-xkb -no-glib -no-gstreamer -no-icu -no-openvg -no-xsync -no-audio-backend -no-sse3 -no-ssse3 -no-sse4.1 -no-sse4.2 -no-avx -no-neon  --prefix=/tgt/qt`

**Comment by keshcode** [comment]
This is due to older docker version

**Comment by keshcode** [comment]
Thank you @ashkulz  , figured out binary generation.This was really usefull https://dev.azure.com/wkhtmltopdf/packaging/_build/results?buildId=12&view=logs&j=38854c4b-8c3d-5a4a-a586-99b1286a488a&t=65ea858f-786c-5dc7-eaee-3c57dc8cd320  Let me know if i can configure improve the documentation.

**Comment by ashkulz** [comment]
If you feel the documentation can be improved, a PR would be great so we can discuss it 👍
