### ISSUE TITLE
Packagist auto-update feature is off

### ISSUE THREAD

**Issue by ghunti** [wkhtmltopdf/packaging#56]
Current version available on Packagist is 0.12.4 instead of 0.12.5. This means that I'm not able to use composer (withouth specifying VCS url) to get the latest version.

**Comment by ghunti** [comment]
Sorry. My bad, the versioning problem is not on your repo!

**Comment by ashkulz** [comment]
That's probably because `0.12.5` doesn't have a generic linux build, see #8
