### ISSUE TITLE
downloads.wkhtmltopdf.org - Certifiate Expiry

### ISSUE THREAD

**Issue by talltom** [wkhtmltopdf/packaging#57]
Hello,

Not sure if this is the right place for this issue, but wanted to let you know that your Let's Encrypt Certificate for https://downloads.wkhtmltopdf.org has expired.

Thanks,

Tomas

**Comment by ashkulz** [comment]
Thanks, fixed it. Please note that it'll be going away on 2020-03-31 -- see wkhtmltopdf/wkhtmltopdf@ba575ea7777a1cc2f3002a3feda4ee2a3e5b2664

**Comment by talltom** [comment]
Thanks @ashkulz.
