### ISSUE TITLE
Ask for help：how to build wkhtmlto×× with the mips64el architecture

### ISSUE THREAD

**Issue by huiji12321** [wkhtmltopdf/packaging#58]
My computer's architecture is mips64el, OS is Fedora 21;and  QMake version 3.1、Using Qt version 5.9.8 in /usr/lib64
When I compile locally like this: 
qmake -o Makefile wkhtmltopdf.pro
make 
make install
then using Error: This version of wkhtmltopdf is built against an unpatched version of QT

When I compile  like this: ./build release ../wkhtmltopdf/,
                                then：exec user process caused "exec format error"
ask for help：How can I build wkhtmlto×× with the mips64el architecture?

**Comment by ashkulz** [comment]
First: I don't see an image for `mips64el` over [at DockerHub](https://hub.docker.com/_/fedora). Also, the version you're using is unsupported -- Fedora 21 is quite old, I think.

If you have a working docker image, then it should be similar to the Raspberry Pi support -- see `build.yml` for how to get it working.

**Comment by ashkulz** [comment]
According to [this page on Fedora wiki](https://fedoraproject.org/wiki/Architectures/MIPS#Releases), the last supported release was Fedora 24 (which is unsupported). It seems Debian is [supported for this architecture](https://wiki.debian.org/MIPSPort), although they call it `mips64el` -- they also have a [image for this arch at DockerHub](https://hub.docker.com/_/debian/?tab=tags&page=1&name=buster).
