### ISSUE TITLE
Missing binary for archlinux/manjaro

### ISSUE THREAD

**Issue by palytoxin** [wkhtmltopdf/packaging#60]
I want to use it on my system. target platform is manjaro. but building from source of this thing is way too hard for me , Is it possible to provide a binary package directly?

**Comment by ashkulz** [comment]
You can try to create a docker-based build using the instructions in `README.md`, but I'm not sure it'll be very useful as ArchLinux is a rolling release distribution, so it'll have to be rebuilt periodically.

**Comment by ashkulz** [comment]
Also, there is [`wkhtmltopdf-static`](https://aur.archlinux.org/packages/wkhtmltopdf-static/), does that not work for you? I think it should be pretty straightforward to port it to ArchLinux -- you'll have to use the [archlinux docker image](https://hub.docker.com/_/archlinux/) and install the necessary packages. [fpm](https://fpm.readthedocs.io/en/latest/) also seems to support pacman packages, so this is something which is doable if you're willing to put in the effort 👍

**Comment by palytoxin** [comment]
> Also, there is [`wkhtmltopdf-static`](https://aur.archlinux.org/packages/wkhtmltopdf-static/), does that not work for you? I think it should be pretty straightforward to port it to ArchLinux -- you'll have to use the [archlinux docker image](https://hub.docker.com/_/archlinux/) and install the necessary packages. [fpm](https://fpm.readthedocs.io/en/latest/) also seems to support pacman packages, so this is something which is doable if you're willing to put in the effort +1

oh, sorry for it, recently I'm working off-site, I had another project to develop that used a different OS,  after a period of time I went back and tried

**Comment by ashkulz** [comment]
So do you not require this now, @palytoxin? Would appreciate closing your issue then, if so.
