### ISSUE TITLE
Request for release 0.12.6

### ISSUE THREAD

**Issue by terry-permeance** [wkhtmltopdf/packaging#61]
Hello,

Thanks for the great utility!

Is there any chance you can build a release for 0.12.6? We need the toc fix so can't use 0.12.5 but don't like running 0.12.6-dev in prod.

Thanks,
Terry

**Comment by ashkulz** [comment]
I'm planning to make a release on the 2-year anniversary of 0.12.5 -- see [the 0.12.6 milestone](https://github.com/wkhtmltopdf/packaging/milestone/2) :crossed_fingers:

**Comment by ashkulz** [comment]
A release candidate for the **0.12.6** release is [now available for download](https://wkhtmltopdf.org/downloads.html#release-candidate), which should contain changes which possibly address this issue.

Would appreciate downloading the package and reporting back if any issues are encountered during testing. Assuming all goes well, I plan to release 0.12.6 on the 2-year anniversary of the previous release i.e. June 11, 2020.
