### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by Kaos-Industries** [wkhtmltopdf/packaging#69]
I've currently managed to get a Cygwin version working by moving installing the Windows binaries and moving everything into Cygwin's own `/bin`, `/include` and `/lib` folders respectively.

Can I expect to be able to use the tool from Cygwin like this without any problems? Will it support converting HTML form fields to fillable PDF equivalents? 

If not, is it possible to get a Cygwin (or alternatively minGW-w64) binary that will, and if so, what steps are needed to do so?

Thank you.

**Comment by ashkulz** [comment]
Please look at the [downloads](https://wkhtmltopdf.org/downloads.html) -- there's both a MSVC 2015 and MXE (mingw-w64) build available.

**Comment by Kaos-Industries** [comment]
As mentioned in the thread, I had already downloaded the MSVC version and was asking whether using these in a Cygwin environment would cause any problems down the line.

**Comment by ashkulz** [comment]
@Kaos-Industries I haven't used Cygwin in quite a while, but I think it can use Windows binaries just fine (except if you use a Cygwin-specific path like `/cygpath` or `/tmp`).
