### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by halkosajtarevic** [wkhtmltopdf/packaging#7]
Any guide how to build this? Which OS is required, what steps have to be taken etc.?

**Comment by ashkulz** [comment]
That's been on my todo list, I'll try to put in some basic docs this
evening. Basically it runs on Ubuntu 18.04, and you need to have the
following packages installed:

sudo apt install python-yaml docker.io vagrant virtualbox p7zip-full

If you want to build for linux, use ./build package-docker or if targeting
Windows or macOS, use ./build vagrant.

**Comment by halkosajtarevic** [comment]
Thank you very much!

**Comment by ashkulz** [comment]
Implemented in 1a23e08d5662fa777b90004970e4ba13d8d4435d, please open PR if you feel something needs to be corrected.
