### ISSUE TITLE
Debian 8 is still supported in 0.12.6?

### ISSUE THREAD

**Issue by pedrofurtado** [wkhtmltopdf/packaging#70]
@ashkulz  I did not find a binary for Debian 8 👍

**Comment by ashkulz** [comment]
Considering that [jessie will be EOL](https://wiki.debian.org/LTS) from this month-end, I didn't bother to make a binary for it. Shouldn't be too tough to add it back just by changing `build.yml`, but I don't think I'll accept PRs for it. You should really upgrade 👍

**Comment by ashkulz** [comment]
See 62ff784f6e520c40b359cdf947c33ac18d04c187 where it was removed.

**Comment by pedrofurtado** [comment]
Thanks for feedback! 🤝

**Comment by ashkulz** [comment]
I've also updated the [release description](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6-1) to mention dropping `jessie` and `trusty`, didn't remember to document it 👍

**Comment by pedrofurtado** [comment]
@ashkulz  Thanks for your hard work on wkhtmltopdf 👍 🤝 🍻
