### ISSUE TITLE
Missing deb for 0.13.0-alpha

### ISSUE THREAD

**Issue by xenyal** [wkhtmltopdf/packaging#74]
Previously the alpha version was available for download through Bitbucket's hosting location here at https://bitbucket.org/wkhtmltopdf/wkhtmltopdf/downloads/wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb.

Was there ever a release packaged for that version on Github? I noticed that it's missing from this repo - not sure if it might be possible to add it back?

**Comment by ashkulz** [comment]
See the [obsolete downloads repo](https://github.com/wkhtmltopdf/obsolete-downloads/releases/tag/0.13.0-alpha).
