### ISSUE TITLE
Ubuntu Focal build for 0.12.2.1

### ISSUE THREAD

**Issue by thorgrin** [wkhtmltopdf/packaging#76]
We've been using version 0.12.2.1 but it is not available or Ubuntu Focal to which we are migrating. Newer versions (tested 0.12.6 and 0.12.4 for which there are OS packages and generic linux binaries respectively) do not generate desired outputs for the same templates. Is is possible to generate the older package/binary for the new Ubuntu Focal?

I've tried building using packaging repository, but it fails on unpatched SSL. Next, I've tried the branch 0.12.1.x which has the patch (again using packaging repository) to see whether it will work, but it failed with
```
python3 ./packaging/build package-docker focal-amd64 `pwd`/wkhtmltopdf
....
....
rm -f libwkhtmltox.so.0.12.7 libwkhtmltox.so libwkhtmltox.so.0 libwkhtmltox.so.0.12
linking ../../bin/libwkhtmltox.so.0.12.7
/usr/bin/ld: cannot find -lQtWebKit
collect2: error: ld returned 1 exit status
make[1]: Leaving directory '/tgt/app/src/lib'
make[1]: *** [Makefile:166: ../../bin/libwkhtmltox.so.0.12.7] Error 1
make: *** [Makefile:61: sub-src-lib-install_subtargets-ordered] Error 2
```

Is there a way to get this package/binary for the latest Ubuntu release?

EDIT:
Sorry, I did not realize that I need to clean the target directory, there was a different QT build already which broke it. The branch 0.12.1.x build just fine. I'll try to apply the SSL patches and see.

**Comment by ashkulz** [comment]
Let me know if the documentation needs to be improved in some way :+1:
