### ISSUE TITLE
Qt not included?

### ISSUE THREAD

**Issue by RoelVdP** [wkhtmltopdf/packaging#80]
ubuntu:~/wkhtmltopdf/packaging$ python build package-docker --clean focal-arm64 "/home/roel/wkhtmltopdf/"
Qt not present in wkhtmltopdf source: /home/roel/wkhtmltopdf/

**Comment by RoelVdP** [comment]
Solved my own issue. I would propose making the build instructions clearer, something along the lines of (this works for me):

```
sudo apt install python-yaml p7zip-full python docker.io
git clone --depth=1 https://github.com/wkhtmltopdf/wkhtmltopdf.git
cd wkhtmltopdf
git clone --depth=1 https://github.com/qt/qtbase.git qt
git clone --depth=1 https://github.com/wkhtmltopdf/packaging.git
cd build
sudo python build package-docker --clean focal-arm64 "${PWD}/../"
```

**Comment by RoelVdP** [comment]
Hmm now I get `Could not detect experimental: true in docker daemon, aborting.`

**Comment by ashkulz** [comment]
Yeah, you need to set the flag to get the multi-arch support working. Would appreciate a PR with updated docs, as it all seems obvious to me 🤷‍♂️
