### ISSUE TITLE
Lambda release

### ISSUE THREAD

**Issue by lnmunhoz** [wkhtmltopdf/packaging#81]
I tried to use the lambda binary that was released, but for some reason it doesn't give me any errors but the pdfs are not generated. However, using the binary from here https://github.com/SebastiaanKlippert/go-wkhtmltopdf-lambda/releases worked.

**Comment by erutherford** [comment]
You should check the version of Amazon linux your lambda is running. The provided archive will only work for lambdas running Amazon Linux 2. https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by ashkulz** [comment]
The zip file has `amazonlinux2_lambda` in the name, so I thought it was implied :slightly_smiling_face:

I'm not sure that it makes sense to support AmazonLinux 1, as it'll be [effectively EOL by year-end](https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/). Not sure what the "maintenance support" means, as the earlier EOL was June 30.

**Comment by erutherford** [comment]
I don't think I said anything about a lack of clarity about what version of Amazon Linux it was for, I was only pointing out that Amazon Linux 2 isn't available for all lambda runtimes and based off the fact that he's referencing a go lambda example he's likely running Amazon Linux 1.

>Beyond December 31, 2020, the Amazon Linux AMI will enter a new maintenance support period that extends to June 30, 2023.
>
>During this maintenance support period:
>
>The Amazon Linux AMI will only receive critical and important security updates for a reduced set of packages.
>It will no longer be guaranteed to support new EC2 platform capabilities, or new AWS features.
Supported packages will include:
>
>The Linux kernel,
>Low-level system libraries such as glibc and openssl,
>Popular packages that are still in a supported state in their upstream sources, such as MySQL and PHP.

The article you reference seems to indicate what they mean by maintenance support. There are quite a few AWS [lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) that are still running Amazon Linux 1 with no indication that they'll be [deprecated](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) any time soon. It also looks like they're intending to maintain Amazon Linux 1 until June 30, 2023. With that in mind are you open to a PR that includes a build for an Amazon Linux 1 variant of the lambda package?

**Comment by ashkulz** [comment]
Sure, if it's not going to be EOL soon I'll happily merge a PR :-)

**Comment by siddhant2308** [comment]
> Sure, if it's not going to be EOL soon I'll happily merge a PR :-)
Can anyone advise on what changes it will take to get the layer for amazonlinux 1. 

(Sorry i am still wrapping my head around all this, but any starting point will be nice).

**Comment by ashkulz** [comment]
I assume it'll be doing similar changes to #77 but for AmazonLinux 1 (by changing `from` to `amazonlinux:1`)?

**Comment by siddhant2308** [comment]
https://github.com/wkhtmltopdf/packaging/blob/b32dc1be3bc278176d73cf15714ea1dbd8deab1e/build.yml#L313
changed to amazonlinux:1
Sorry for over-simplify things here, but in the packaging repo (wkhtmltopdf repo in parallel)
running command:
./build package-docker amazonlinux2_lambda ../wkhtmltopdf, and expecting a zip output. This is taking some while to complete.

**Comment by ashkulz** [comment]
Considering AmazonLinux 1 is EOL this monthend, I'm going to close this issue.
