### ISSUE TITLE
Can't run compiled binaries on Azure Windows Server

### ISSUE THREAD

**Issue by junalmeida** [wkhtmltopdf/packaging#83]
I tried with both `mxe-cross` and `msvc` versions, compiled for `x64`. This happens only on a Azure App Service. 

![image](https://user-images.githubusercontent.com/991675/101227331-152c1100-365d-11eb-8ee6-04182f55c24c.png)

**Comment by junalmeida** [comment]
Just found the issue. Sorry

**Comment by ashkulz** [comment]
What was the issue, @junalmeida?
