### ISSUE TITLE
Windows Silent Install

### ISSUE THREAD

**Issue by mrdalrymple** [wkhtmltopdf/packaging#87]
For automated installs / installing in a Windows Docker container, installers need to not show up any prompts.

I am not able to use the "/s" option when running the Windows installer to get it to "silently" install.

See: https://stackoverflow.com/questions/14445395/nullsoft-scriptable-install-system-nsis-installer-silent-mode 
Which points to one example: https://nsis.sourceforge.io/Examples/silent.nsi

**Comment by ashkulz** [comment]
I think it's `/S`, not `/s`. Please post screenshots of what you're getting, as this is something that used to work reliably earlier -- it's included in Chocolatey and quite a few other places, which use this functionality.

**Comment by ashkulz** [comment]
Please reopen the issue, if it doesn't work for you with a detailed scenario which doesn't work.
