### ISSUE TITLE
Flatpak or Snappy packages?

### ISSUE THREAD

**Issue by qhartman** [wkhtmltopdf/packaging#9]
I am wondering is using flatpak (my preference) or snappy packages might help get around the complexities of running in different Linux environments?

flatpak - https://flatpak.org/
snappy snapcraft - https://snapcraft.io/

Thoughts on that?

**Comment by ashkulz** [comment]
Patches welcome, or even a detailed guide would help.

**Comment by Tomsgu** [comment]
I don't have too much time to look into this (in comming days), but [here](http://docs.flatpak.org/en/latest/building.html) is a complete guide for flatpak as this is also my preference. 

[Here](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) are also main reasons to use it.

**Comment by ashkulz** [comment]
I'm not sure that makes sense for CLI tools like wkhtmltopdf, which are often bundled along with another application -- as opposed to GUI applications. In addition, the revamped setup which I've merged recently makes it very easy to build for any target distribution.

Either way, considering that no one has stepped up -- I'm going to close the issue for now. If anyone does submit a PR for implementing such a thing, I'd be happy to merge it 👍
