### ISSUE TITLE
About the Android version

### ISSUE THREAD

**Issue by yforq** [wkhtmltopdf/packaging#91]
hi bosses ，How do I build an Android version?  I tried to compile it several times and frustratingly failed.

**Comment by ashkulz** [comment]
I have absolutely no clue, but I doubt it will work because I don't think Qt 4.x (_which wkhtmltopdf uses_) supports Android.

**Comment by yforq** [comment]
sir，Thanks for your reply!Can I try to compile it with Qt 5.1?Since WebKit was killed after 5.6, does wkhtml2image need any 4.x features other than WebKit?

**Comment by ashkulz** [comment]
You can try, but it'll be the unpatched version which may require an X server ... not sure how that'll work on Android.

**Comment by mddanishansari** [comment]
Getting in the queue and waiting for the time when it's available for Android.

**Comment by ashkulz** [comment]
@mddanishansari like I said above, I'm not sure how/if it will work, see above comment :man_shrugging:
