### ISSUE TITLE
sh: xvfb-run: command not found

### ISSUE THREAD

**Issue by JitendraSSingh** [wkhtmltopdf/packaging#96]
Hi there,

Firstly thank you for creating a seperate repo for packaging, really appreciate that. 

So I am following along the example which is given in the repo for generating .zip for different targets, in my case it is I want it for `amazonlinux2_lambda`. I am building the package on an AWS EC2 instance which uses `ubuntu-focal-20.04-amd64-server-20210223` as AMI, after zipping the package and creating a layer on the Lambda function which I have when I am executing one of my php function(uses a wrapper around wkhtmltopdf), it complaints for `xvfb` , `sh: xvfb-run: command not found`. I am following exact instruction which is given on the repo readme . And the .zip is getting generated successfully. I can see different folders which has this structure.
.
├── bin
│   ├── wkhtmltoimage
│   └── wkhtmltopdf
├── fonts
│   ├── dejavu
│   │   ├── DejaVuSans-Bold.ttf
│   │   ├── DejaVuSans-BoldOblique.ttf
│   │   ├── DejaVuSans-ExtraLight.ttf
│   │   ├── DejaVuSans-Oblique.ttf
│   │   ├── DejaVuSans.ttf
│   │   ├── DejaVuSansCondensed-Bold.ttf
│   │   ├── DejaVuSansCondensed-BoldOblique.ttf
│   │   ├── DejaVuSansCondensed-Oblique.ttf
│   │   └── DejaVuSansCondensed.ttf
│   └── fonts.conf
└── lib
      ├── libX11.so.6
      ├── libXau.so.6
      ├── libXext.so.6
      ├── libXrender.so.1
      ├── libbz2.so.1
      ├── libexpat.so.1
      ├── libfontconfig.so.1
      ├── libfreetype.so.6
      ├── libjpeg.so.62
      ├── libpng15.so.15
      ├── libuuid.so.1
      └── libxcb.so.1 
Do I need to install `xvfb` as a seperate layer ?, or does this packaging takes care of it ?.

Thank you.

**Comment by ashkulz** [comment]
Not sure what you mean -- you mention `amazonlinux2_lambda` and then talk of 'ubuntu-focal`, both are different distros. Why don't you simply install the [focal deb](https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb) in case you're using the latter?

**Comment by JitendraSSingh** [comment]
Hey @ashkulz  sorry for the confusion over there, what I meant was that, the target for which I was generating the Binaries was for `amazonlinux2_lambda`. Actually just an update, I have managed to have compiled version of `wkhtmltopdf` to run on AWS Lamda, the issue where I am running into is when I try to use `xvfb` along with `wkhtmltopdf`. It looks like this issue is more of `xvfb`. Will close the issue for now, if I have any findings will update again. Anyways thank you for looking into it. :)
