### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by yishairasowsky** [wkhtmltopdf/packaging#97]
Hi! I love your work. I am trying to make page numbers alternately appear at the bottom left for odd pages and bottom right for even pages. Is there a way to do that?
What I have so far is this...

```
wkhtmltopdf_path = 'C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe'
config = pdfkit.configuration(wkhtmltopdf=wkhtmltopdf_path)
options = {
    'footer-center': '~ [page] of [topage] ~',
```

**Comment by ashkulz** [comment]
Please use `--footer-html`, and this is the wrong repo to ask questions like this.

**Comment by yishairasowsky** [comment]
@ashkulz thank you for your reply! where is the right place to ask? is there documentation for `--footer-html` where i can see what it is and how to use it? thanks!
